/* Generated by Yosys 0.9+3981 (git sha1 375af199, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:3.1-152.10" *)
module xy_router(x_addr, y_addr, mux_out_sel_o);
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:106.5-131.8" *)
  wire [2:0] _00_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:106.5-131.8" *)
  wire [2:0] _01_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:106.5-131.8" *)
  wire [2:0] _02_;
  wire [1:0] _03_;
  wire [1:0] _04_;
  wire _05_;
  wire [1:0] _06_;
  wire _07_;
  (* force_downto = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122.15-122.30|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [3:0] _08_;
  (* force_downto = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122.15-122.30|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* force_downto = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114.20-114.35|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [3:0] _13_;
  (* force_downto = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114.20-114.35|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "0 1" *)
  wire [3:0] _14_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122.15-122.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _15_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122.15-122.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _16_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114.20-114.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _17_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114.20-114.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _18_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114.20-114.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _19_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:39.34-39.38" *)
  wire [2:0] DOWN;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:36.34-36.38" *)
  wire [2:0] LEFT;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:35.34-35.42" *)
  wire [2:0] RESOURCE;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:38.34-38.39" *)
  wire [2:0] RIGHT;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:37.34-37.36" *)
  wire [2:0] UP;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:15.31-15.44" *)
  output [2:0] mux_out_sel_o;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:24.28-24.41" *)
  wire [2:0] mux_out_sel_w;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:13.36-13.42" *)
  input [3:0] x_addr;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:27.34-27.40" *)
  wire [3:0] x_cord;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:14.36-14.42" *)
  input [3:0] y_addr;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:28.34-28.40" *)
  wire [3:0] y_cord;
  assign _14_[3] = ~y_addr[3];
  assign _14_[2] = ~y_addr[2];
  assign _09_[2] = ~x_addr[2];
  assign _09_[3] = ~x_addr[3];
  assign _09_[1] = ~x_addr[1];
  assign _09_[0] = ~x_addr[0];
  assign _03_[0] = _09_[0] &(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122.15-122.30" *)  _09_[1];
  assign _03_[1] = _09_[2] &(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122.15-122.30" *)  _09_[3];
  assign _11_ = _03_[0] &(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122.15-122.30" *)  _03_[1];
  assign _04_[0] = x_addr[0] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:108.13-108.29" *)  x_addr[1];
  assign _04_[1] = x_addr[2] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:108.13-108.29" *)  x_addr[3];
  assign _05_ = _04_[0] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:108.13-108.29" *)  _04_[1];
  assign _06_[0] = y_addr[0] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:110.15-110.31" *)  y_addr[1];
  assign _06_[1] = y_addr[2] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:110.15-110.31" *)  y_addr[3];
  assign _07_ = _06_[0] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:110.15-110.31" *)  _06_[1];
  assign _02_[1] = ~(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122.15-122.30|../srcs/switch/simple_mesh_xy/router_xy.v:122.11-128.14" *) _12_;
  assign _01_[0] = ~(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114.20-114.35|../srcs/switch/simple_mesh_xy/router_xy.v:114.16-119.14" *) _13_[3];
  assign _00_[0] = _07_ ? (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:110.15-110.31|../srcs/switch/simple_mesh_xy/router_xy.v:110.11-119.14" *) _01_[0] : 1'h0;
  assign mux_out_sel_o[0] = _05_ ? (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:108.13-108.29|../srcs/switch/simple_mesh_xy/router_xy.v:108.9-129.12" *) 1'h0 : _00_[0];
  assign mux_out_sel_o[1] = _05_ ? (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:108.13-108.29|../srcs/switch/simple_mesh_xy/router_xy.v:108.9-129.12" *) _02_[1] : 1'h0;
  assign _10_ = ~(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122.15-122.30" *) _08_[3];
  assign _12_ = _10_ | _11_;
  assign _17_ = _14_[3] &(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114.20-114.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  y_addr[2];
  assign _18_ = _14_[3] &(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114.20-114.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _14_[2];
  assign _19_ = y_addr[3] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114.20-114.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _17_;
  assign _13_[3] = _19_ |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114.20-114.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _18_;
  assign _15_ = _09_[3] &(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122.15-122.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  x_addr[2];
  assign _16_ = x_addr[3] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122.15-122.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _15_;
  assign _08_[3] = _16_ |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122.15-122.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _03_[1];
  assign _00_[2:1] = 2'h0;
  assign _01_[2:1] = 2'h0;
  assign { _02_[2], _02_[0] } = 2'h0;
  assign _08_[2:0] = 3'h7;
  assign _13_[2:0] = 3'h7;
  assign DOWN = 3'h0;
  assign LEFT = 3'h0;
  assign RESOURCE = 3'h0;
  assign RIGHT = 3'h2;
  assign UP = 3'h1;
  assign mux_out_sel_o[2] = 1'h0;
  assign mux_out_sel_w = { 1'h0, mux_out_sel_o[1:0] };
  assign x_cord = 4'h0;
  assign y_cord = 4'h0;
endmodule
