/* Generated by Yosys 0.9+3981 (git sha1 375af199, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:38.1-182.10" *)
module xy_switch(clk_i, rst_ni, wr_en_sw_i, pckt_sw_i, in_fifo_full_o, in_fifo_overflow_o, nxt_fifo_full_i, nxt_fifo_overflow_i, wr_en_sw_o, pckt_sw_o);
  wire [1:0] _00_;
  wire _01_;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.25-180.37" *)
  wire _02_;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:52.11-52.16" *)
  input clk_i;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:72.37-72.47" *)
  wire [79:0] data_out_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:86.39-86.46" *)
  wire [4:0] empty_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:84.39-84.54" *)
  wire [79:0] fifo_data_out_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:91.30-91.41" *)
  wire [15:0] \genfifo[0].x_pckt_in_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:92.30-92.42" *)
  wire [15:0] \genfifo[0].x_pckt_out_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:91.30-91.41" *)
  wire [15:0] \genfifo[1].x_pckt_in_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:92.30-92.42" *)
  wire [15:0] \genfifo[1].x_pckt_out_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:91.30-91.41" *)
  wire [15:0] \genfifo[2].x_pckt_in_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:92.30-92.42" *)
  wire [15:0] \genfifo[2].x_pckt_out_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:91.30-91.41" *)
  wire [15:0] \genfifo[3].x_pckt_in_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:92.30-92.42" *)
  wire [15:0] \genfifo[3].x_pckt_out_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:91.30-91.41" *)
  wire [15:0] \genfifo[4].x_pckt_in_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:92.30-92.42" *)
  wire [15:0] \genfifo[4].x_pckt_out_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:58.41-58.55" *)
  output [4:0] in_fifo_full_o;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:59.41-59.59" *)
  output [4:0] in_fifo_overflow_o;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:70.37-70.49" *)
  wire [2:0] mux_in_sel_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:71.37-71.50" *)
  wire [2:0] mux_out_sel_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:62.41-62.56" *)
  input [4:0] nxt_fifo_full_i;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:63.41-63.60" *)
  input [4:0] nxt_fifo_overflow_i;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:73.37-73.53" *)
  wire [15:0] pckt_in_chosen_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:57.41-57.50" *)
  input [79:0] pckt_sw_i;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:65.41-65.50" *)
  output [79:0] pckt_sw_o;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:85.39-85.46" *)
  wire [4:0] rd_en_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:53.11-53.17" *)
  input rst_ni;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:87.39-87.50" *)
  wire [4:0] underflow_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:69.37-69.48" *)
  wire [4:0] vld_input_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:56.41-56.51" *)
  input [4:0] wr_en_sw_i;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:64.41-64.51" *)
  output [4:0] wr_en_sw_o;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:76.33-76.41" *)
  wire [3:0] x_addr_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:77.33-77.41" *)
  wire [3:0] y_addr_w;
  assign _00_[0] = vld_input_w[0] |(* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.25-180.37" *)  vld_input_w[1];
  assign _00_[1] = vld_input_w[2] |(* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.25-180.37" *)  vld_input_w[3];
  assign _01_ = _00_[0] |(* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.25-180.37" *)  _00_[1];
  assign _02_ = _01_ |(* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.25-180.37" *)  vld_input_w[4];
  assign pckt_sw_o[16] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[16] : 1'h0;
  assign pckt_sw_o[17] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[17] : 1'h0;
  assign pckt_sw_o[18] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[18] : 1'h0;
  assign pckt_sw_o[19] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[19] : 1'h0;
  assign pckt_sw_o[20] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[20] : 1'h0;
  assign pckt_sw_o[21] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[21] : 1'h0;
  assign pckt_sw_o[22] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[22] : 1'h0;
  assign pckt_sw_o[23] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[23] : 1'h0;
  assign pckt_sw_o[24] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[24] : 1'h0;
  assign pckt_sw_o[25] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[25] : 1'h0;
  assign pckt_sw_o[26] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[26] : 1'h0;
  assign pckt_sw_o[27] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[27] : 1'h0;
  assign pckt_sw_o[28] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[28] : 1'h0;
  assign pckt_sw_o[29] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[29] : 1'h0;
  assign pckt_sw_o[30] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[30] : 1'h0;
  assign pckt_sw_o[31] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[31] : 1'h0;
  assign pckt_sw_o[32] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[32] : 1'h0;
  assign pckt_sw_o[33] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[33] : 1'h0;
  assign pckt_sw_o[34] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[34] : 1'h0;
  assign pckt_sw_o[35] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[35] : 1'h0;
  assign pckt_sw_o[36] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[36] : 1'h0;
  assign pckt_sw_o[37] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[37] : 1'h0;
  assign pckt_sw_o[38] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[38] : 1'h0;
  assign pckt_sw_o[39] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[39] : 1'h0;
  assign pckt_sw_o[40] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[40] : 1'h0;
  assign pckt_sw_o[41] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[41] : 1'h0;
  assign pckt_sw_o[42] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[42] : 1'h0;
  assign pckt_sw_o[43] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[43] : 1'h0;
  assign pckt_sw_o[44] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[44] : 1'h0;
  assign pckt_sw_o[45] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[45] : 1'h0;
  assign pckt_sw_o[46] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[46] : 1'h0;
  assign pckt_sw_o[47] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[47] : 1'h0;
  assign pckt_sw_o[48] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[48] : 1'h0;
  assign pckt_sw_o[49] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[49] : 1'h0;
  assign pckt_sw_o[50] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[50] : 1'h0;
  assign pckt_sw_o[51] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[51] : 1'h0;
  assign pckt_sw_o[52] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[52] : 1'h0;
  assign pckt_sw_o[53] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[53] : 1'h0;
  assign pckt_sw_o[54] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[54] : 1'h0;
  assign pckt_sw_o[55] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[55] : 1'h0;
  assign pckt_sw_o[56] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[56] : 1'h0;
  assign pckt_sw_o[57] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[57] : 1'h0;
  assign pckt_sw_o[58] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[58] : 1'h0;
  assign pckt_sw_o[59] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[59] : 1'h0;
  assign pckt_sw_o[60] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[60] : 1'h0;
  assign pckt_sw_o[61] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[61] : 1'h0;
  assign pckt_sw_o[62] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[62] : 1'h0;
  assign pckt_sw_o[63] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[63] : 1'h0;
  assign pckt_sw_o[64] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[64] : 1'h0;
  assign pckt_sw_o[65] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[65] : 1'h0;
  assign pckt_sw_o[66] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[66] : 1'h0;
  assign pckt_sw_o[67] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[67] : 1'h0;
  assign pckt_sw_o[68] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[68] : 1'h0;
  assign pckt_sw_o[69] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[69] : 1'h0;
  assign pckt_sw_o[70] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[70] : 1'h0;
  assign pckt_sw_o[71] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[71] : 1'h0;
  assign pckt_sw_o[72] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[72] : 1'h0;
  assign pckt_sw_o[73] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[73] : 1'h0;
  assign pckt_sw_o[74] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[74] : 1'h0;
  assign pckt_sw_o[75] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[75] : 1'h0;
  assign pckt_sw_o[76] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[76] : 1'h0;
  assign pckt_sw_o[77] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[77] : 1'h0;
  assign pckt_sw_o[78] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[78] : 1'h0;
  assign pckt_sw_o[79] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[79] : 1'h0;
  assign pckt_sw_o[0] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[0] : 1'h0;
  assign pckt_sw_o[1] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[1] : 1'h0;
  assign pckt_sw_o[2] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[2] : 1'h0;
  assign pckt_sw_o[3] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[3] : 1'h0;
  assign pckt_sw_o[4] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[4] : 1'h0;
  assign pckt_sw_o[5] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[5] : 1'h0;
  assign pckt_sw_o[6] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[6] : 1'h0;
  assign pckt_sw_o[7] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[7] : 1'h0;
  assign pckt_sw_o[8] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[8] : 1'h0;
  assign pckt_sw_o[9] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[9] : 1'h0;
  assign pckt_sw_o[10] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[10] : 1'h0;
  assign pckt_sw_o[11] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[11] : 1'h0;
  assign pckt_sw_o[12] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[12] : 1'h0;
  assign pckt_sw_o[13] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[13] : 1'h0;
  assign pckt_sw_o[14] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[14] : 1'h0;
  assign pckt_sw_o[15] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:180.24-180.55" *) data_out_w[15] : 1'h0;
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:123.5-127.10" *)
  arbiter #(
    .PORT_N(32'sd5)
  ) arb (
    .mux_in_sel_o(mux_in_sel_w),
    .vld_input_i(vld_input_w)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:150.5-161.10" *)
  control_unit #(
    .PORT_N(32'sd5)
  ) control_u (
    .clk_i(clk_i),
    .empty_i(empty_w),
    .full_i(nxt_fifo_full_i),
    .mux_in_sel_i(mux_in_sel_w),
    .mux_out_sel_i(mux_out_sel_w),
    .rd_en_o(rd_en_w),
    .rst_ni(rst_ni),
    .vld_input_o(vld_input_w),
    .wr_en_o(wr_en_sw_o)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:169.5-178.10" *)
  n_to_n_crossbar #(
    .DATA_WIDTH(32'sd16),
    .PORT_N(32'sd5)
  ) crossbar (
    .clk_i(clk_i),
    .data_i(fifo_data_out_w),
    .data_o(data_out_w),
    .mux_in_sel_i(mux_in_sel_w),
    .mux_out_sel_i(mux_out_sel_w),
    .pckt_in_chosen_o(pckt_in_chosen_w),
    .rst_ni(rst_ni)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:100.9-112.14" *)
  fifo #(
    .DATA_WIDTH(32'sd16),
    .FIFO_DEPTH_WIDTH(32'sd3),
    .ID(32'sd0)
  ) \genfifo[0].x_input_fifo  (
    .clk_i(clk_i),
    .data_i(pckt_sw_i[15:0]),
    .data_o(fifo_data_out_w[15:0]),
    .empty_o(empty_w[0]),
    .full_o(in_fifo_full_o[0]),
    .overflow_o(in_fifo_overflow_o[0]),
    .rd_en_i(rd_en_w[0]),
    .rst_ni(rst_ni),
    .underflow_o(underflow_w[0]),
    .wr_en_i(wr_en_sw_i[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:100.9-112.14" *)
  fifo #(
    .DATA_WIDTH(32'sd16),
    .FIFO_DEPTH_WIDTH(32'sd3),
    .ID(32'sd1)
  ) \genfifo[1].x_input_fifo  (
    .clk_i(clk_i),
    .data_i(pckt_sw_i[31:16]),
    .data_o(fifo_data_out_w[31:16]),
    .empty_o(empty_w[1]),
    .full_o(in_fifo_full_o[1]),
    .overflow_o(in_fifo_overflow_o[1]),
    .rd_en_i(rd_en_w[1]),
    .rst_ni(rst_ni),
    .underflow_o(underflow_w[1]),
    .wr_en_i(wr_en_sw_i[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:100.9-112.14" *)
  fifo #(
    .DATA_WIDTH(32'sd16),
    .FIFO_DEPTH_WIDTH(32'sd3),
    .ID(32'sd2)
  ) \genfifo[2].x_input_fifo  (
    .clk_i(clk_i),
    .data_i(pckt_sw_i[47:32]),
    .data_o(fifo_data_out_w[47:32]),
    .empty_o(empty_w[2]),
    .full_o(in_fifo_full_o[2]),
    .overflow_o(in_fifo_overflow_o[2]),
    .rd_en_i(rd_en_w[2]),
    .rst_ni(rst_ni),
    .underflow_o(underflow_w[2]),
    .wr_en_i(wr_en_sw_i[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:100.9-112.14" *)
  fifo #(
    .DATA_WIDTH(32'sd16),
    .FIFO_DEPTH_WIDTH(32'sd3),
    .ID(32'sd3)
  ) \genfifo[3].x_input_fifo  (
    .clk_i(clk_i),
    .data_i(pckt_sw_i[63:48]),
    .data_o(fifo_data_out_w[63:48]),
    .empty_o(empty_w[3]),
    .full_o(in_fifo_full_o[3]),
    .overflow_o(in_fifo_overflow_o[3]),
    .rd_en_i(rd_en_w[3]),
    .rst_ni(rst_ni),
    .underflow_o(underflow_w[3]),
    .wr_en_i(wr_en_sw_i[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:100.9-112.14" *)
  fifo #(
    .DATA_WIDTH(32'sd16),
    .FIFO_DEPTH_WIDTH(32'sd3),
    .ID(32'sd4)
  ) \genfifo[4].x_input_fifo  (
    .clk_i(clk_i),
    .data_i(pckt_sw_i[79:64]),
    .data_o(fifo_data_out_w[79:64]),
    .empty_o(empty_w[4]),
    .full_o(in_fifo_full_o[4]),
    .overflow_o(in_fifo_overflow_o[4]),
    .rd_en_i(rd_en_w[4]),
    .rst_ni(rst_ni),
    .underflow_o(underflow_w[4]),
    .wr_en_i(wr_en_sw_i[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:138.5-143.10" *)
  xy_router #(
    .OUTPUT_N_W(32'sd3),
    .PACKET_ADDR_X_W(32'sd4),
    .PACKET_ADDR_Y_W(32'sd4),
    .X_CORD(32'sd0),
    .Y_CORD(32'sd0)
  ) router (
    .mux_out_sel_o(mux_out_sel_w),
    .x_addr(pckt_in_chosen_w[15:12]),
    .y_addr(pckt_in_chosen_w[11:8])
  );
  assign \genfifo[0].x_pckt_in_w  = pckt_sw_i[15:0];
  assign \genfifo[0].x_pckt_out_w  = fifo_data_out_w[15:0];
  assign \genfifo[1].x_pckt_in_w  = pckt_sw_i[31:16];
  assign \genfifo[1].x_pckt_out_w  = fifo_data_out_w[31:16];
  assign \genfifo[2].x_pckt_in_w  = pckt_sw_i[47:32];
  assign \genfifo[2].x_pckt_out_w  = fifo_data_out_w[47:32];
  assign \genfifo[3].x_pckt_in_w  = pckt_sw_i[63:48];
  assign \genfifo[3].x_pckt_out_w  = fifo_data_out_w[63:48];
  assign \genfifo[4].x_pckt_in_w  = pckt_sw_i[79:64];
  assign \genfifo[4].x_pckt_out_w  = fifo_data_out_w[79:64];
  assign x_addr_w = pckt_in_chosen_w[15:12];
  assign y_addr_w = pckt_in_chosen_w[11:8];
endmodule
