/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:2" *)
module arbiter(vld_input_i, mux_in_sel_o);
  (* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:15" *)
  wire [2:0] _00_;
  (* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:15" *)
  wire [2:0] _01_;
  (* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:15" *)
  wire [2:0] _02_;
  wire _03_;
  wire [1:0] _04_;
  wire _05_;
  (* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:8" *)
  output [2:0] mux_in_sel_o;
  (* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:11" *)
  wire [2:0] mux_in_sel_w;
  (* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:7" *)
  input [4:0] vld_input_i;
  assign _04_[0] = vld_input_i[4] |(* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:17" *)  vld_input_i[3];
  assign _04_[1] = vld_input_i[2] |(* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:17" *)  vld_input_i[1];
  assign _05_ = _04_[0] |(* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:17" *)  _04_[1];
  assign _03_ = _05_ |(* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:17" *)  vld_input_i[0];
  assign _02_[0] = vld_input_i[2] ? (* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:29" *) 1'h0 : vld_input_i[1];
  assign _01_[0] = vld_input_i[3] ? (* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:24" *) 1'h1 : _02_[0];
  assign _01_[1] = vld_input_i[3] ? (* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:24" *) 1'h1 : vld_input_i[2];
  assign _00_[0] = vld_input_i[4] ? (* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:19" *) 1'h0 : _01_[0];
  assign _00_[1] = vld_input_i[4] ? (* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:19" *) 1'h0 : _01_[1];
  (* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:15" *)
  \$_DLATCH_P_  _15_ (
    .D(_00_[0]),
    .E(_03_),
    .Q(mux_in_sel_w[0])
  );
  (* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:15" *)
  \$_DLATCH_P_  _16_ (
    .D(_00_[1]),
    .E(_03_),
    .Q(mux_in_sel_w[1])
  );
  (* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:15" *)
  \$_DLATCH_P_  _17_ (
    .D(vld_input_i[4]),
    .E(_03_),
    .Q(mux_in_sel_w[2])
  );
  assign _00_[2] = vld_input_i[4];
  assign _01_[2] = 1'h0;
  assign _02_[2:1] = { 1'h0, vld_input_i[2] };
  assign mux_in_sel_o = mux_in_sel_w;
endmodule

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:6" *)
module control_unit(clk_i, rst_ni, empty_i, rd_en_o, vld_input_o, full_i, wr_en_o, mux_in_sel_i, mux_out_sel_i);
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:37" *)
  wire [4:0] _000_;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *)
  (* unused_bits = "5 6 7" *)
  wire [31:0] _001_;
  wire [1:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire [2:0] _009_;
  wire [2:0] _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *)
  wire [31:0] _015_;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:31" *)
  wire [4:0] _016_;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:46" *)
  wire [4:0] _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *)
  wire _024_;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *)
  (* unused_bits = "5 6 7" *)
  wire [31:0] _025_;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:47|<techmap.v>:145" *)
  (* unused_bits = "4" *)
  wire [4:0] _026_;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:47|<techmap.v>:145" *)
  (* unused_bits = "2 3 4" *)
  wire [4:0] _027_;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32|<techmap.v>:102" *)
  wire [31:0] _028_;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32|<techmap.v>:102" *)
  wire [31:0] _029_;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:11" *)
  input clk_i;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:15" *)
  input [4:0] empty_i;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:20" *)
  input [4:0] full_i;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:24" *)
  input [2:0] mux_in_sel_i;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:25" *)
  input [2:0] mux_out_sel_i;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:16" *)
  output [4:0] rd_en_o;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:31" *)
  wire [4:0] rd_en_w;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:12" *)
  input rst_ni;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:17" *)
  output [4:0] vld_input_o;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:29" *)
  reg [4:0] vld_input_v;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:21" *)
  output [4:0] wr_en_o;
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *)
  wire [4:0] wr_en_w;
  assign _002_[0] = vld_input_v[4] |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *)  vld_input_v[3];
  assign _002_[1] = vld_input_v[2] |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *)  vld_input_v[1];
  assign _003_ = _002_[0] |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *)  _002_[1];
  assign _024_ = _003_ |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *)  vld_input_v[0];
  assign _004_ = _009_[0] |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:49" *)  _009_[1];
  assign _011_ = _004_ |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:49" *)  mux_in_sel_i[2];
  assign _005_ = mux_in_sel_i[0] |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:49" *)  mux_in_sel_i[1];
  assign _012_ = _005_ |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:49" *)  _010_[2];
  assign _006_ = _009_[0] |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:49" *)  mux_in_sel_i[1];
  assign _013_ = _006_ |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:49" *)  mux_in_sel_i[2];
  assign _007_ = mux_in_sel_i[0] |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:49" *)  _009_[1];
  assign _014_ = _007_ |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:49" *)  mux_in_sel_i[2];
  assign _008_ = _005_ |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:49" *)  mux_in_sel_i[2];
  assign wr_en_w[0] = _024_ ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *) _001_[0] : 1'h0;
  assign wr_en_w[1] = _024_ ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *) _001_[1] : 1'h0;
  assign wr_en_w[2] = _024_ ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *) _001_[2] : 1'h0;
  assign wr_en_w[3] = _024_ ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *) _001_[3] : 1'h0;
  assign wr_en_w[4] = _024_ ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *) _001_[4] : 1'h0;
  assign _022_ = _012_ ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:49" *) _017_[4] : 1'h0;
  assign _000_[4] = _019_ ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:47" *) _022_ : _017_[4];
  assign _023_ = _011_ ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:49" *) _017_[3] : 1'h0;
  assign _000_[3] = _019_ ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:47" *) _023_ : _017_[3];
  assign _018_ = _014_ ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:49" *) _017_[2] : 1'h0;
  assign _000_[2] = _019_ ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:47" *) _018_ : _017_[2];
  assign _020_ = _013_ ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:49" *) _017_[1] : 1'h0;
  assign _000_[1] = _019_ ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:47" *) _020_ : _017_[1];
  assign _021_ = _008_ ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:49" *) _017_[0] : 1'h0;
  assign _000_[0] = _019_ ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:47" *) _021_ : _017_[0];
  assign _026_[0] = mux_out_sel_i[2] ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:47|<techmap.v>:162" *) wr_en_w[4] : wr_en_w[0];
  assign _026_[1] = mux_out_sel_i[2] ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:47|<techmap.v>:162" *) 1'hx : wr_en_w[1];
  assign _026_[2] = mux_out_sel_i[2] ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:47|<techmap.v>:162" *) 1'hx : wr_en_w[2];
  assign _026_[3] = mux_out_sel_i[2] ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:47|<techmap.v>:162" *) 1'hx : wr_en_w[3];
  assign _027_[0] = mux_out_sel_i[1] ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:47|<techmap.v>:162" *) _026_[2] : _026_[0];
  assign _027_[1] = mux_out_sel_i[1] ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:47|<techmap.v>:162" *) _026_[3] : _026_[1];
  assign _019_ = mux_out_sel_i[0] ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:47|<techmap.v>:162" *) _027_[1] : _027_[0];
  assign rd_en_w[0] = ~(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:31" *) _016_[0];
  assign rd_en_w[1] = ~(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:31" *) _016_[1];
  assign rd_en_w[2] = ~(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:31" *) _016_[2];
  assign rd_en_w[3] = ~(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:31" *) _016_[3];
  assign rd_en_w[4] = ~(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:31" *) _016_[4];
  assign _015_[0] = ~(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *) full_i[0];
  assign _015_[1] = ~(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *) full_i[1];
  assign _015_[2] = ~(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *) full_i[2];
  assign _015_[3] = ~(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *) full_i[3];
  assign _015_[4] = ~(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *) full_i[4];
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:37" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      vld_input_v[0] <= 0;
    else
      vld_input_v[0] <= _000_[0];
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:37" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      vld_input_v[1] <= 0;
    else
      vld_input_v[1] <= _000_[1];
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:37" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      vld_input_v[2] <= 0;
    else
      vld_input_v[2] <= _000_[2];
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:37" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      vld_input_v[3] <= 0;
    else
      vld_input_v[3] <= _000_[3];
  (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:37" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      vld_input_v[4] <= 0;
    else
      vld_input_v[4] <= _000_[4];
  assign _016_[0] = empty_i[0] |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:31" *)  vld_input_v[0];
  assign _016_[1] = empty_i[1] |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:31" *)  vld_input_v[1];
  assign _016_[2] = empty_i[2] |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:31" *)  vld_input_v[2];
  assign _016_[3] = empty_i[3] |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:31" *)  vld_input_v[3];
  assign _016_[4] = empty_i[4] |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:31" *)  vld_input_v[4];
  assign _001_[0] = _025_[0] &(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *)  _015_[0];
  assign _001_[1] = _025_[1] &(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *)  _015_[1];
  assign _001_[2] = _025_[2] &(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *)  _015_[2];
  assign _001_[3] = _025_[3] &(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *)  _015_[3];
  assign _001_[4] = _025_[4] &(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32" *)  _015_[4];
  assign _017_[0] = rd_en_w[0] |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:46" *)  vld_input_v[0];
  assign _017_[1] = rd_en_w[1] |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:46" *)  vld_input_v[1];
  assign _017_[2] = rd_en_w[2] |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:46" *)  vld_input_v[2];
  assign _017_[3] = rd_en_w[3] |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:46" *)  vld_input_v[3];
  assign _017_[4] = rd_en_w[4] |(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:46" *)  vld_input_v[4];
  assign _009_[0] = mux_in_sel_i[0] ^(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:49" *)  1'h1;
  assign _009_[1] = mux_in_sel_i[1] ^(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:49" *)  1'h1;
  assign _010_[2] = mux_in_sel_i[2] ^(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:49" *)  1'h1;
  assign _025_[0] = mux_out_sel_i[2] ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32|<techmap.v>:107" *) 1'h0 : _029_[0];
  assign _025_[1] = mux_out_sel_i[2] ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32|<techmap.v>:107" *) 1'h0 : _029_[1];
  assign _025_[2] = mux_out_sel_i[2] ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32|<techmap.v>:107" *) 1'h0 : _029_[2];
  assign _025_[3] = mux_out_sel_i[2] ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32|<techmap.v>:107" *) 1'h0 : _029_[3];
  assign _025_[4] = mux_out_sel_i[2] ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32|<techmap.v>:107" *) _029_[0] : 1'h0;
  assign _028_[0] = ~(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32|<techmap.v>:107" *) mux_out_sel_i[0];
  assign _029_[0] = mux_out_sel_i[1] ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32|<techmap.v>:107" *) 1'h0 : _028_[0];
  assign _029_[1] = mux_out_sel_i[1] ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32|<techmap.v>:107" *) 1'h0 : mux_out_sel_i[0];
  assign _029_[2] = mux_out_sel_i[1] ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32|<techmap.v>:107" *) _028_[0] : 1'h0;
  assign _029_[3] = mux_out_sel_i[1] ? (* src = "../srcs/switch/simple_mesh_xy/control_unit.v:32|<techmap.v>:107" *) mux_out_sel_i[0] : 1'h0;
  assign _001_[31:8] = 24'h000000;
  assign _009_[2] = mux_in_sel_i[2];
  assign _010_[1:0] = mux_in_sel_i[1:0];
  assign _015_[31:5] = 27'h7ffffff;
  assign _025_[31:5] = { 24'h000000, _001_[7:5] };
  assign _028_[31:1] = { 30'h00000000, mux_out_sel_i[0] };
  assign _029_[31:4] = 28'h0000000;
  assign rd_en_o = rd_en_w;
  assign vld_input_o = vld_input_v;
  assign wr_en_o = wr_en_w;
endmodule

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "../srcs/components/fifo.v:6" *)
module fifo(clk_i, rst_ni, wr_en_i, rd_en_i, data_i, data_o, full_o, empty_o, overflow_o, underflow_o);
  (* src = "../srcs/components/fifo.v:73" *)
  wire [7:0] _000_;
  (* src = "../srcs/components/fifo.v:46" *)
  wire [7:0] _001_;
  (* src = "../srcs/components/fifo.v:46" *)
  wire [7:0] _002_;
  (* src = "../srcs/components/fifo.v:46" *)
  wire [7:0] _003_;
  (* src = "../srcs/components/fifo.v:46" *)
  wire [7:0] _004_;
  (* src = "../srcs/components/fifo.v:46" *)
  wire _005_;
  (* src = "../srcs/components/fifo.v:73" *)
  wire [1:0] _006_;
  (* src = "../srcs/components/fifo.v:73" *)
  wire _007_;
  (* src = "../srcs/components/fifo.v:46" *)
  wire [1:0] _008_;
  (* src = "../srcs/components/fifo.v:73" *)
  wire [7:0] _009_;
  (* src = "../srcs/components/fifo.v:42" *)
  wire [1:0] _010_;
  (* src = "../srcs/components/fifo.v:83" *)
  wire [1:0] _011_;
  wire [1:0] _012_;
  wire [1:0] _013_;
  wire [1:0] _014_;
  wire [1:0] _015_;
  wire [1:0] _016_;
  wire [1:0] _017_;
  wire [1:0] _018_;
  wire [1:0] _019_;
  wire [1:0] _020_;
  wire _021_;
  wire _022_;
  wire [1:0] _023_;
  wire [1:0] _024_;
  wire [1:0] _025_;
  wire [1:0] _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  (* src = "../srcs/components/fifo.v:56" *)
  wire _035_;
  (* src = "../srcs/components/fifo.v:6|<techmap.v>:432" *)
  wire [31:0] _036_;
  (* src = "../srcs/components/fifo.v:6|<techmap.v>:428" *)
  wire [7:0] _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire [1:0] _042_;
  wire [7:0] _043_;
  wire [7:0] _044_;
  wire [7:0] _045_;
  wire [7:0] _046_;
  wire [7:0] _047_;
  wire [7:0] _048_;
  wire [7:0] _049_;
  wire [7:0] _050_;
  wire [7:0] _051_;
  wire _052_;
  wire [1:0] _053_;
  (* src = "../srcs/components/fifo.v:6|<techmap.v>:445" *)
  wire _054_;
  (* src = "../srcs/components/fifo.v:13" *)
  input clk_i;
  (* src = "../srcs/components/fifo.v:17" *)
  input [7:0] data_i;
  (* src = "../srcs/components/fifo.v:18" *)
  output [7:0] data_o;
  (* src = "../srcs/components/fifo.v:35" *)
  reg [7:0] data_v;
  (* src = "../srcs/components/fifo.v:20" *)
  output empty_o;
  (* src = "../srcs/components/fifo.v:41" *)
  wire empty_w;
  (* src = "../srcs/components/fifo.v:6" *)
  reg [7:0] \fifo_v[0] ;
  (* src = "../srcs/components/fifo.v:6" *)
  reg [7:0] \fifo_v[1] ;
  (* src = "../srcs/components/fifo.v:6" *)
  reg [7:0] \fifo_v[2] ;
  (* src = "../srcs/components/fifo.v:6" *)
  reg [7:0] \fifo_v[3] ;
  (* src = "../srcs/components/fifo.v:19" *)
  output full_o;
  (* src = "../srcs/components/fifo.v:41" *)
  wire full_w;
  (* src = "../srcs/components/fifo.v:21" *)
  output overflow_o;
  (* src = "../srcs/components/fifo.v:38" *)
  reg overflow_v;
  (* src = "../srcs/components/fifo.v:16" *)
  input rd_en_i;
  (* src = "../srcs/components/fifo.v:37" *)
  reg [1:0] rd_ptr_v;
  (* src = "../srcs/components/fifo.v:14" *)
  input rst_ni;
  (* src = "../srcs/components/fifo.v:22" *)
  output underflow_o;
  (* src = "../srcs/components/fifo.v:38" *)
  reg underflow_v;
  (* src = "../srcs/components/fifo.v:15" *)
  input wr_en_i;
  (* src = "../srcs/components/fifo.v:37" *)
  reg [1:0] wr_ptr_v;
  assign _027_ = _023_[0] |(* src = "../srcs/components/fifo.v:42" *)  _023_[1];
  assign _028_ = _024_[0] |(* src = "../srcs/components/fifo.v:43" *)  _024_[1];
  assign _029_ = _011_[0] |(* src = "../srcs/components/fifo.v:6" *)  _025_[1];
  assign _030_ = rd_ptr_v[0] |(* src = "../srcs/components/fifo.v:6" *)  _025_[1];
  assign _031_ = _011_[0] |(* src = "../srcs/components/fifo.v:6" *)  rd_ptr_v[1];
  assign _032_ = _010_[0] |(* src = "../srcs/components/fifo.v:6" *)  _026_[1];
  assign _033_ = wr_ptr_v[0] |(* src = "../srcs/components/fifo.v:6" *)  _026_[1];
  assign _034_ = _010_[0] |(* src = "../srcs/components/fifo.v:6" *)  wr_ptr_v[1];
  assign _012_[0] = _036_[0] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _036_[8];
  assign _012_[1] = _036_[16] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _036_[24];
  assign _037_[0] = _012_[0] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _012_[1];
  assign _013_[0] = _036_[1] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _036_[9];
  assign _013_[1] = _036_[17] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _036_[25];
  assign _037_[1] = _013_[0] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _013_[1];
  assign _014_[0] = _036_[2] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _036_[10];
  assign _014_[1] = _036_[18] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _036_[26];
  assign _037_[2] = _014_[0] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _014_[1];
  assign _015_[0] = _036_[3] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _036_[11];
  assign _015_[1] = _036_[19] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _036_[27];
  assign _037_[3] = _015_[0] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _015_[1];
  assign _016_[0] = _036_[4] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _036_[12];
  assign _016_[1] = _036_[20] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _036_[28];
  assign _037_[4] = _016_[0] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _016_[1];
  assign _017_[0] = _036_[6] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _036_[14];
  assign _017_[1] = _036_[22] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _036_[30];
  assign _037_[6] = _017_[0] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _017_[1];
  assign _018_[0] = _036_[7] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _036_[15];
  assign _018_[1] = _036_[23] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _036_[31];
  assign _037_[7] = _018_[0] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _018_[1];
  assign _019_[0] = _036_[5] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _036_[13];
  assign _019_[1] = _036_[21] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _036_[29];
  assign _037_[5] = _019_[0] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:441" *)  _019_[1];
  assign _020_[0] = _038_ |(* src = "../srcs/components/fifo.v:6|<techmap.v>:445" *)  _039_;
  assign _020_[1] = _040_ |(* src = "../srcs/components/fifo.v:6|<techmap.v>:445" *)  _041_;
  assign _054_ = _020_[0] |(* src = "../srcs/components/fifo.v:6|<techmap.v>:445" *)  _020_[1];
  assign _021_ = rd_ptr_v[0] |(* src = "../srcs/components/fifo.v:6" *)  rd_ptr_v[1];
  assign _022_ = wr_ptr_v[0] |(* src = "../srcs/components/fifo.v:6" *)  wr_ptr_v[1];
  assign full_o = ~(* src = "../srcs/components/fifo.v:42" *) _027_;
  assign empty_o = ~(* src = "../srcs/components/fifo.v:43" *) _028_;
  assign _038_ = ~(* src = "../srcs/components/fifo.v:6" *) _029_;
  assign _039_ = ~(* src = "../srcs/components/fifo.v:6" *) _030_;
  assign _040_ = ~(* src = "../srcs/components/fifo.v:6" *) _031_;
  assign _041_ = ~(* src = "../srcs/components/fifo.v:6" *) _021_;
  assign _035_ = _027_ |(* src = "../srcs/components/fifo.v:56" *)  rd_en_i;
  assign underflow_o = _028_ ? (* src = "../srcs/components/fifo.v:92" *) 1'h0 : underflow_v;
  assign _042_[0] = _028_ ? (* src = "../srcs/components/fifo.v:81" *) _011_[0] : rd_ptr_v[0];
  assign _042_[1] = _028_ ? (* src = "../srcs/components/fifo.v:81" *) _011_[1] : rd_ptr_v[1];
  assign _007_ = rd_en_i ? (* src = "../srcs/components/fifo.v:80" *) empty_o : underflow_o;
  assign _006_[0] = rd_en_i ? (* src = "../srcs/components/fifo.v:80" *) _042_[0] : rd_ptr_v[0];
  assign _006_[1] = rd_en_i ? (* src = "../srcs/components/fifo.v:80" *) _042_[1] : rd_ptr_v[1];
  assign _043_[0] = _028_ ? (* src = "../srcs/components/fifo.v:81" *) _009_[0] : data_v[0];
  assign _043_[1] = _028_ ? (* src = "../srcs/components/fifo.v:81" *) _009_[1] : data_v[1];
  assign _043_[2] = _028_ ? (* src = "../srcs/components/fifo.v:81" *) _009_[2] : data_v[2];
  assign _043_[3] = _028_ ? (* src = "../srcs/components/fifo.v:81" *) _009_[3] : data_v[3];
  assign _043_[4] = _028_ ? (* src = "../srcs/components/fifo.v:81" *) _009_[4] : data_v[4];
  assign _043_[5] = _028_ ? (* src = "../srcs/components/fifo.v:81" *) _009_[5] : data_v[5];
  assign _043_[6] = _028_ ? (* src = "../srcs/components/fifo.v:81" *) _009_[6] : data_v[6];
  assign _043_[7] = _028_ ? (* src = "../srcs/components/fifo.v:81" *) _009_[7] : data_v[7];
  assign _000_[0] = rd_en_i ? (* src = "../srcs/components/fifo.v:80" *) _043_[0] : data_v[0];
  assign _000_[1] = rd_en_i ? (* src = "../srcs/components/fifo.v:80" *) _043_[1] : data_v[1];
  assign _000_[2] = rd_en_i ? (* src = "../srcs/components/fifo.v:80" *) _043_[2] : data_v[2];
  assign _000_[3] = rd_en_i ? (* src = "../srcs/components/fifo.v:80" *) _043_[3] : data_v[3];
  assign _000_[4] = rd_en_i ? (* src = "../srcs/components/fifo.v:80" *) _043_[4] : data_v[4];
  assign _000_[5] = rd_en_i ? (* src = "../srcs/components/fifo.v:80" *) _043_[5] : data_v[5];
  assign _000_[6] = rd_en_i ? (* src = "../srcs/components/fifo.v:80" *) _043_[6] : data_v[6];
  assign _000_[7] = rd_en_i ? (* src = "../srcs/components/fifo.v:80" *) _043_[7] : data_v[7];
  assign _044_[0] = _032_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[3] [0] : data_i[0];
  assign _044_[1] = _032_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[3] [1] : data_i[1];
  assign _044_[2] = _032_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[3] [2] : data_i[2];
  assign _044_[3] = _032_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[3] [3] : data_i[3];
  assign _044_[4] = _032_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[3] [4] : data_i[4];
  assign _044_[5] = _032_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[3] [5] : data_i[5];
  assign _044_[6] = _032_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[3] [6] : data_i[6];
  assign _044_[7] = _032_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[3] [7] : data_i[7];
  assign _045_[0] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _044_[0] : \fifo_v[3] [0];
  assign _045_[1] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _044_[1] : \fifo_v[3] [1];
  assign _045_[2] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _044_[2] : \fifo_v[3] [2];
  assign _045_[3] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _044_[3] : \fifo_v[3] [3];
  assign _045_[4] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _044_[4] : \fifo_v[3] [4];
  assign _045_[5] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _044_[5] : \fifo_v[3] [5];
  assign _045_[6] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _044_[6] : \fifo_v[3] [6];
  assign _045_[7] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _044_[7] : \fifo_v[3] [7];
  assign _004_[0] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _045_[0] : \fifo_v[3] [0];
  assign _004_[1] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _045_[1] : \fifo_v[3] [1];
  assign _004_[2] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _045_[2] : \fifo_v[3] [2];
  assign _004_[3] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _045_[3] : \fifo_v[3] [3];
  assign _004_[4] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _045_[4] : \fifo_v[3] [4];
  assign _004_[5] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _045_[5] : \fifo_v[3] [5];
  assign _004_[6] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _045_[6] : \fifo_v[3] [6];
  assign _004_[7] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _045_[7] : \fifo_v[3] [7];
  assign _046_[0] = _033_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[2] [0] : data_i[0];
  assign _046_[1] = _033_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[2] [1] : data_i[1];
  assign _046_[2] = _033_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[2] [2] : data_i[2];
  assign _046_[3] = _033_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[2] [3] : data_i[3];
  assign _046_[4] = _033_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[2] [4] : data_i[4];
  assign _046_[5] = _033_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[2] [5] : data_i[5];
  assign _046_[6] = _033_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[2] [6] : data_i[6];
  assign _046_[7] = _033_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[2] [7] : data_i[7];
  assign _047_[0] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _046_[0] : \fifo_v[2] [0];
  assign _047_[1] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _046_[1] : \fifo_v[2] [1];
  assign _047_[2] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _046_[2] : \fifo_v[2] [2];
  assign _047_[3] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _046_[3] : \fifo_v[2] [3];
  assign _047_[4] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _046_[4] : \fifo_v[2] [4];
  assign _047_[5] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _046_[5] : \fifo_v[2] [5];
  assign _047_[6] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _046_[6] : \fifo_v[2] [6];
  assign _047_[7] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _046_[7] : \fifo_v[2] [7];
  assign _003_[0] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _047_[0] : \fifo_v[2] [0];
  assign _003_[1] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _047_[1] : \fifo_v[2] [1];
  assign _003_[2] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _047_[2] : \fifo_v[2] [2];
  assign _003_[3] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _047_[3] : \fifo_v[2] [3];
  assign _003_[4] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _047_[4] : \fifo_v[2] [4];
  assign _003_[5] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _047_[5] : \fifo_v[2] [5];
  assign _003_[6] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _047_[6] : \fifo_v[2] [6];
  assign _003_[7] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _047_[7] : \fifo_v[2] [7];
  assign _048_[0] = _034_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[1] [0] : data_i[0];
  assign _048_[1] = _034_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[1] [1] : data_i[1];
  assign _048_[2] = _034_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[1] [2] : data_i[2];
  assign _048_[3] = _034_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[1] [3] : data_i[3];
  assign _048_[4] = _034_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[1] [4] : data_i[4];
  assign _048_[5] = _034_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[1] [5] : data_i[5];
  assign _048_[6] = _034_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[1] [6] : data_i[6];
  assign _048_[7] = _034_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[1] [7] : data_i[7];
  assign _049_[0] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _048_[0] : \fifo_v[1] [0];
  assign _049_[1] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _048_[1] : \fifo_v[1] [1];
  assign _049_[2] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _048_[2] : \fifo_v[1] [2];
  assign _049_[3] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _048_[3] : \fifo_v[1] [3];
  assign _049_[4] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _048_[4] : \fifo_v[1] [4];
  assign _049_[5] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _048_[5] : \fifo_v[1] [5];
  assign _049_[6] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _048_[6] : \fifo_v[1] [6];
  assign _049_[7] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _048_[7] : \fifo_v[1] [7];
  assign _002_[0] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _049_[0] : \fifo_v[1] [0];
  assign _002_[1] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _049_[1] : \fifo_v[1] [1];
  assign _002_[2] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _049_[2] : \fifo_v[1] [2];
  assign _002_[3] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _049_[3] : \fifo_v[1] [3];
  assign _002_[4] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _049_[4] : \fifo_v[1] [4];
  assign _002_[5] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _049_[5] : \fifo_v[1] [5];
  assign _002_[6] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _049_[6] : \fifo_v[1] [6];
  assign _002_[7] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _049_[7] : \fifo_v[1] [7];
  assign _050_[0] = _022_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[0] [0] : data_i[0];
  assign _050_[1] = _022_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[0] [1] : data_i[1];
  assign _050_[2] = _022_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[0] [2] : data_i[2];
  assign _050_[3] = _022_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[0] [3] : data_i[3];
  assign _050_[4] = _022_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[0] [4] : data_i[4];
  assign _050_[5] = _022_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[0] [5] : data_i[5];
  assign _050_[6] = _022_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[0] [6] : data_i[6];
  assign _050_[7] = _022_ ? (* src = "../srcs/components/fifo.v:6" *) \fifo_v[0] [7] : data_i[7];
  assign _051_[0] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _050_[0] : \fifo_v[0] [0];
  assign _051_[1] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _050_[1] : \fifo_v[0] [1];
  assign _051_[2] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _050_[2] : \fifo_v[0] [2];
  assign _051_[3] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _050_[3] : \fifo_v[0] [3];
  assign _051_[4] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _050_[4] : \fifo_v[0] [4];
  assign _051_[5] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _050_[5] : \fifo_v[0] [5];
  assign _051_[6] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _050_[6] : \fifo_v[0] [6];
  assign _051_[7] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _050_[7] : \fifo_v[0] [7];
  assign _001_[0] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _051_[0] : \fifo_v[0] [0];
  assign _001_[1] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _051_[1] : \fifo_v[0] [1];
  assign _001_[2] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _051_[2] : \fifo_v[0] [2];
  assign _001_[3] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _051_[3] : \fifo_v[0] [3];
  assign _001_[4] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _051_[4] : \fifo_v[0] [4];
  assign _001_[5] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _051_[5] : \fifo_v[0] [5];
  assign _001_[6] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _051_[6] : \fifo_v[0] [6];
  assign _001_[7] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _051_[7] : \fifo_v[0] [7];
  assign _005_ = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _052_ : overflow_o;
  assign overflow_o = _027_ ? (* src = "../srcs/components/fifo.v:67" *) 1'h0 : overflow_v;
  assign _052_ = ~(* src = "../srcs/components/fifo.v:56" *) _035_;
  assign _053_[0] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _010_[0] : wr_ptr_v[0];
  assign _053_[1] = _035_ ? (* src = "../srcs/components/fifo.v:56" *) _010_[1] : wr_ptr_v[1];
  assign _008_[0] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _053_[0] : wr_ptr_v[0];
  assign _008_[1] = wr_en_i ? (* src = "../srcs/components/fifo.v:55" *) _053_[1] : wr_ptr_v[1];
  assign _009_[0] = _054_ ? (* src = "../srcs/components/fifo.v:6|<techmap.v>:445" *) _037_[0] : 1'hx;
  assign _009_[1] = _054_ ? (* src = "../srcs/components/fifo.v:6|<techmap.v>:445" *) _037_[1] : 1'hx;
  assign _009_[2] = _054_ ? (* src = "../srcs/components/fifo.v:6|<techmap.v>:445" *) _037_[2] : 1'hx;
  assign _009_[3] = _054_ ? (* src = "../srcs/components/fifo.v:6|<techmap.v>:445" *) _037_[3] : 1'hx;
  assign _009_[4] = _054_ ? (* src = "../srcs/components/fifo.v:6|<techmap.v>:445" *) _037_[4] : 1'hx;
  assign _009_[5] = _054_ ? (* src = "../srcs/components/fifo.v:6|<techmap.v>:445" *) _037_[5] : 1'hx;
  assign _009_[6] = _054_ ? (* src = "../srcs/components/fifo.v:6|<techmap.v>:445" *) _037_[6] : 1'hx;
  assign _009_[7] = _054_ ? (* src = "../srcs/components/fifo.v:6|<techmap.v>:445" *) _037_[7] : 1'hx;
  (* src = "../srcs/components/fifo.v:73" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      data_v[0] <= 0;
    else
      data_v[0] <= _000_[0];
  (* src = "../srcs/components/fifo.v:73" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      data_v[1] <= 0;
    else
      data_v[1] <= _000_[1];
  (* src = "../srcs/components/fifo.v:73" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      data_v[2] <= 0;
    else
      data_v[2] <= _000_[2];
  (* src = "../srcs/components/fifo.v:73" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      data_v[3] <= 0;
    else
      data_v[3] <= _000_[3];
  (* src = "../srcs/components/fifo.v:73" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      data_v[4] <= 0;
    else
      data_v[4] <= _000_[4];
  (* src = "../srcs/components/fifo.v:73" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      data_v[5] <= 0;
    else
      data_v[5] <= _000_[5];
  (* src = "../srcs/components/fifo.v:73" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      data_v[6] <= 0;
    else
      data_v[6] <= _000_[6];
  (* src = "../srcs/components/fifo.v:73" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      data_v[7] <= 0;
    else
      data_v[7] <= _000_[7];
  (* src = "../srcs/components/fifo.v:73" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      rd_ptr_v[0] <= 0;
    else
      rd_ptr_v[0] <= _006_[0];
  (* src = "../srcs/components/fifo.v:73" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      rd_ptr_v[1] <= 0;
    else
      rd_ptr_v[1] <= _006_[1];
  (* src = "../srcs/components/fifo.v:73" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      underflow_v <= 0;
    else
      underflow_v <= _007_;
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      wr_ptr_v[0] <= 0;
    else
      wr_ptr_v[0] <= _008_[0];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      wr_ptr_v[1] <= 0;
    else
      wr_ptr_v[1] <= _008_[1];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      overflow_v <= 0;
    else
      overflow_v <= _005_;
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[0] [0] <= 0;
    else
      \fifo_v[0] [0] <= _001_[0];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[0] [1] <= 0;
    else
      \fifo_v[0] [1] <= _001_[1];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[0] [2] <= 0;
    else
      \fifo_v[0] [2] <= _001_[2];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[0] [3] <= 0;
    else
      \fifo_v[0] [3] <= _001_[3];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[0] [4] <= 0;
    else
      \fifo_v[0] [4] <= _001_[4];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[0] [5] <= 0;
    else
      \fifo_v[0] [5] <= _001_[5];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[0] [6] <= 0;
    else
      \fifo_v[0] [6] <= _001_[6];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[0] [7] <= 0;
    else
      \fifo_v[0] [7] <= _001_[7];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[1] [0] <= 0;
    else
      \fifo_v[1] [0] <= _002_[0];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[1] [1] <= 0;
    else
      \fifo_v[1] [1] <= _002_[1];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[1] [2] <= 0;
    else
      \fifo_v[1] [2] <= _002_[2];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[1] [3] <= 0;
    else
      \fifo_v[1] [3] <= _002_[3];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[1] [4] <= 0;
    else
      \fifo_v[1] [4] <= _002_[4];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[1] [5] <= 0;
    else
      \fifo_v[1] [5] <= _002_[5];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[1] [6] <= 0;
    else
      \fifo_v[1] [6] <= _002_[6];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[1] [7] <= 0;
    else
      \fifo_v[1] [7] <= _002_[7];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[2] [0] <= 0;
    else
      \fifo_v[2] [0] <= _003_[0];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[2] [1] <= 0;
    else
      \fifo_v[2] [1] <= _003_[1];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[2] [2] <= 0;
    else
      \fifo_v[2] [2] <= _003_[2];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[2] [3] <= 0;
    else
      \fifo_v[2] [3] <= _003_[3];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[2] [4] <= 0;
    else
      \fifo_v[2] [4] <= _003_[4];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[2] [5] <= 0;
    else
      \fifo_v[2] [5] <= _003_[5];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[2] [6] <= 0;
    else
      \fifo_v[2] [6] <= _003_[6];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[2] [7] <= 0;
    else
      \fifo_v[2] [7] <= _003_[7];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[3] [0] <= 0;
    else
      \fifo_v[3] [0] <= _004_[0];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[3] [1] <= 0;
    else
      \fifo_v[3] [1] <= _004_[1];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[3] [2] <= 0;
    else
      \fifo_v[3] [2] <= _004_[2];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[3] [3] <= 0;
    else
      \fifo_v[3] [3] <= _004_[3];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[3] [4] <= 0;
    else
      \fifo_v[3] [4] <= _004_[4];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[3] [5] <= 0;
    else
      \fifo_v[3] [5] <= _004_[5];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[3] [6] <= 0;
    else
      \fifo_v[3] [6] <= _004_[6];
  (* src = "../srcs/components/fifo.v:46" *)
  always @(posedge clk_i or negedge rst_ni)
    if (!rst_ni)
      \fifo_v[3] [7] <= 0;
    else
      \fifo_v[3] [7] <= _004_[7];
  assign _023_[0] = _010_[0] ^(* src = "../srcs/components/fifo.v:42" *)  rd_ptr_v[0];
  assign _023_[1] = _010_[1] ^(* src = "../srcs/components/fifo.v:42" *)  rd_ptr_v[1];
  assign _024_[0] = wr_ptr_v[0] ^(* src = "../srcs/components/fifo.v:43" *)  rd_ptr_v[0];
  assign _024_[1] = wr_ptr_v[1] ^(* src = "../srcs/components/fifo.v:43" *)  rd_ptr_v[1];
  assign _025_[1] = rd_ptr_v[1] ^(* src = "../srcs/components/fifo.v:6" *)  1'h1;
  assign _011_[0] = rd_ptr_v[0] ^(* src = "../srcs/components/fifo.v:6" *)  1'h1;
  assign _026_[1] = wr_ptr_v[1] ^(* src = "../srcs/components/fifo.v:6" *)  1'h1;
  assign _010_[0] = wr_ptr_v[0] ^(* src = "../srcs/components/fifo.v:6" *)  1'h1;
  assign _036_[24] = \fifo_v[0] [0] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _041_;
  assign _036_[25] = \fifo_v[0] [1] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _041_;
  assign _036_[26] = \fifo_v[0] [2] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _041_;
  assign _036_[27] = \fifo_v[0] [3] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _041_;
  assign _036_[28] = \fifo_v[0] [4] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _041_;
  assign _036_[29] = \fifo_v[0] [5] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _041_;
  assign _036_[30] = \fifo_v[0] [6] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _041_;
  assign _036_[31] = \fifo_v[0] [7] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _041_;
  assign _036_[0] = \fifo_v[3] [0] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _038_;
  assign _036_[1] = \fifo_v[3] [1] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _038_;
  assign _036_[2] = \fifo_v[3] [2] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _038_;
  assign _036_[3] = \fifo_v[3] [3] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _038_;
  assign _036_[4] = \fifo_v[3] [4] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _038_;
  assign _036_[5] = \fifo_v[3] [5] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _038_;
  assign _036_[6] = \fifo_v[3] [6] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _038_;
  assign _036_[7] = \fifo_v[3] [7] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _038_;
  assign _036_[8] = \fifo_v[2] [0] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _039_;
  assign _036_[9] = \fifo_v[2] [1] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _039_;
  assign _036_[10] = \fifo_v[2] [2] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _039_;
  assign _036_[11] = \fifo_v[2] [3] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _039_;
  assign _036_[12] = \fifo_v[2] [4] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _039_;
  assign _036_[13] = \fifo_v[2] [5] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _039_;
  assign _036_[14] = \fifo_v[2] [6] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _039_;
  assign _036_[15] = \fifo_v[2] [7] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _039_;
  assign _036_[16] = \fifo_v[1] [0] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _040_;
  assign _036_[17] = \fifo_v[1] [1] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _040_;
  assign _036_[18] = \fifo_v[1] [2] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _040_;
  assign _036_[19] = \fifo_v[1] [3] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _040_;
  assign _036_[20] = \fifo_v[1] [4] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _040_;
  assign _036_[21] = \fifo_v[1] [5] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _040_;
  assign _036_[22] = \fifo_v[1] [6] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _040_;
  assign _036_[23] = \fifo_v[1] [7] &(* src = "../srcs/components/fifo.v:6|<techmap.v>:434" *)  _040_;
  assign _010_[1] = wr_ptr_v[1] ^(* src = "../srcs/components/fifo.v:42|<techmap.v>:263" *)  wr_ptr_v[0];
  assign _011_[1] = rd_ptr_v[1] ^(* src = "../srcs/components/fifo.v:83|../srcs/components/fifo.v:42|<techmap.v>:263" *)  rd_ptr_v[0];
  assign _025_[0] = _011_[0];
  assign _026_[0] = _010_[0];
  assign data_o = data_v;
  assign empty_w = empty_o;
  assign full_w = full_o;
endmodule

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)
module n_to_n_crossbar(clk_i, rst_ni, data_i, mux_in_sel_i, mux_out_sel_i, pckt_in_chosen_o, data_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire [1:0] _008_;
  wire _009_;
  wire [1:0] _010_;
  wire _011_;
  wire [1:0] _012_;
  wire _013_;
  wire [1:0] _014_;
  wire _015_;
  wire [1:0] _016_;
  wire _017_;
  wire [1:0] _018_;
  wire _019_;
  wire [1:0] _020_;
  wire _021_;
  wire [1:0] _022_;
  wire _023_;
  wire [1:0] _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire [2:0] _028_;
  wire [2:0] _029_;
  wire [2:0] _030_;
  wire [2:0] _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:432" *)
  wire [39:0] _040_;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:428" *)
  wire [7:0] _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:445" *)
  wire _047_;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:21" *)
  input clk_i;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:24" *)
  input [39:0] data_i;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:29" *)
  output [39:0] data_o;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:48" *)
  wire [31:0] i;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)
  wire [7:0] \mux_in[0] ;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)
  wire [7:0] \mux_in[1] ;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)
  wire [7:0] \mux_in[2] ;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)
  wire [7:0] \mux_in[3] ;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)
  wire [7:0] \mux_in[4] ;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:44" *)
  wire [7:0] mux_in_data_chosen_w;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:25" *)
  input [2:0] mux_in_sel_i;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)
  wire [7:0] \mux_out_data_v[0] ;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)
  wire [7:0] \mux_out_data_v[1] ;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)
  wire [7:0] \mux_out_data_v[2] ;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)
  wire [7:0] \mux_out_data_v[3] ;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)
  wire [7:0] \mux_out_data_v[4] ;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:26" *)
  input [2:0] mux_out_sel_i;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:28" *)
  output [7:0] pckt_in_chosen_o;
  (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:22" *)
  input rst_ni;
  assign _032_ = _000_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  _028_[2];
  assign _001_ = _029_[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  _029_[1];
  assign _033_ = _001_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  mux_in_sel_i[2];
  assign _002_ = mux_in_sel_i[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  _029_[1];
  assign _034_ = _002_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  mux_in_sel_i[2];
  assign _003_ = _029_[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  mux_in_sel_i[1];
  assign _035_ = _003_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  mux_in_sel_i[2];
  assign _004_ = mux_out_sel_i[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  mux_out_sel_i[1];
  assign _036_ = _004_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  _030_[2];
  assign _005_ = _031_[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  _031_[1];
  assign _037_ = _005_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  mux_out_sel_i[2];
  assign _006_ = mux_out_sel_i[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  _031_[1];
  assign _038_ = _006_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  mux_out_sel_i[2];
  assign _007_ = _031_[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  mux_out_sel_i[1];
  assign _039_ = _007_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  mux_out_sel_i[2];
  assign _008_[0] = _040_[7] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[15];
  assign _008_[1] = _040_[23] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[31];
  assign _009_ = _008_[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _008_[1];
  assign _041_[7] = _009_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[39];
  assign _010_[0] = _040_[6] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[14];
  assign _010_[1] = _040_[22] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[30];
  assign _011_ = _010_[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _010_[1];
  assign _041_[6] = _011_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[38];
  assign _012_[0] = _040_[5] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[13];
  assign _012_[1] = _040_[21] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[29];
  assign _013_ = _012_[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _012_[1];
  assign _041_[5] = _013_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[37];
  assign _014_[0] = _040_[4] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[12];
  assign _014_[1] = _040_[20] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[28];
  assign _015_ = _014_[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _014_[1];
  assign _041_[4] = _015_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[36];
  assign _016_[0] = _040_[3] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[11];
  assign _016_[1] = _040_[19] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[27];
  assign _017_ = _016_[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _016_[1];
  assign _041_[3] = _017_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[35];
  assign _018_[0] = _040_[2] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[10];
  assign _018_[1] = _040_[18] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[26];
  assign _019_ = _018_[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _018_[1];
  assign _041_[2] = _019_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[34];
  assign _020_[0] = _040_[1] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[9];
  assign _020_[1] = _040_[17] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[25];
  assign _021_ = _020_[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _020_[1];
  assign _041_[1] = _021_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[33];
  assign _022_[0] = _040_[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[8];
  assign _022_[1] = _040_[16] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[24];
  assign _023_ = _022_[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _022_[1];
  assign _041_[0] = _023_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:441" *)  _040_[32];
  assign _024_[0] = _042_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:445" *)  _043_;
  assign _024_[1] = _044_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:445" *)  _045_;
  assign _025_ = _024_[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:445" *)  _024_[1];
  assign _047_ = _025_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:445" *)  _046_;
  assign _000_ = mux_in_sel_i[0] |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  mux_in_sel_i[1];
  assign _026_ = _000_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  mux_in_sel_i[2];
  assign _027_ = _004_ |(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  mux_out_sel_i[2];
  assign _042_ = ~(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) _032_;
  assign _043_ = ~(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) _033_;
  assign _044_ = ~(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) _034_;
  assign _045_ = ~(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) _035_;
  assign _046_ = ~(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) _026_;
  assign \mux_out_data_v[0] [0] = _027_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[0];
  assign \mux_out_data_v[0] [1] = _027_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[1];
  assign \mux_out_data_v[0] [2] = _027_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[2];
  assign \mux_out_data_v[0] [3] = _027_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[3];
  assign \mux_out_data_v[0] [4] = _027_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[4];
  assign \mux_out_data_v[0] [5] = _027_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[5];
  assign \mux_out_data_v[0] [6] = _027_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[6];
  assign \mux_out_data_v[0] [7] = _027_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[7];
  assign \mux_out_data_v[4] [0] = _036_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[0];
  assign \mux_out_data_v[4] [1] = _036_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[1];
  assign \mux_out_data_v[4] [2] = _036_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[2];
  assign \mux_out_data_v[4] [3] = _036_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[3];
  assign \mux_out_data_v[4] [4] = _036_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[4];
  assign \mux_out_data_v[4] [5] = _036_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[5];
  assign \mux_out_data_v[4] [6] = _036_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[6];
  assign \mux_out_data_v[4] [7] = _036_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[7];
  assign \mux_out_data_v[3] [0] = _037_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[0];
  assign \mux_out_data_v[3] [1] = _037_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[1];
  assign \mux_out_data_v[3] [2] = _037_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[2];
  assign \mux_out_data_v[3] [3] = _037_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[3];
  assign \mux_out_data_v[3] [4] = _037_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[4];
  assign \mux_out_data_v[3] [5] = _037_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[5];
  assign \mux_out_data_v[3] [6] = _037_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[6];
  assign \mux_out_data_v[3] [7] = _037_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[7];
  assign \mux_out_data_v[2] [0] = _038_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[0];
  assign \mux_out_data_v[2] [1] = _038_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[1];
  assign \mux_out_data_v[2] [2] = _038_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[2];
  assign \mux_out_data_v[2] [3] = _038_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[3];
  assign \mux_out_data_v[2] [4] = _038_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[4];
  assign \mux_out_data_v[2] [5] = _038_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[5];
  assign \mux_out_data_v[2] [6] = _038_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[6];
  assign \mux_out_data_v[2] [7] = _038_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[7];
  assign \mux_out_data_v[1] [0] = _039_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[0];
  assign \mux_out_data_v[1] [1] = _039_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[1];
  assign \mux_out_data_v[1] [2] = _039_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[2];
  assign \mux_out_data_v[1] [3] = _039_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[3];
  assign \mux_out_data_v[1] [4] = _039_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[4];
  assign \mux_out_data_v[1] [5] = _039_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[5];
  assign \mux_out_data_v[1] [6] = _039_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[6];
  assign \mux_out_data_v[1] [7] = _039_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *) 1'h0 : mux_in_data_chosen_w[7];
  assign mux_in_data_chosen_w[0] = _047_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:445" *) _041_[0] : 1'hx;
  assign mux_in_data_chosen_w[1] = _047_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:445" *) _041_[1] : 1'hx;
  assign mux_in_data_chosen_w[2] = _047_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:445" *) _041_[2] : 1'hx;
  assign mux_in_data_chosen_w[3] = _047_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:445" *) _041_[3] : 1'hx;
  assign mux_in_data_chosen_w[4] = _047_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:445" *) _041_[4] : 1'hx;
  assign mux_in_data_chosen_w[5] = _047_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:445" *) _041_[5] : 1'hx;
  assign mux_in_data_chosen_w[6] = _047_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:445" *) _041_[6] : 1'hx;
  assign mux_in_data_chosen_w[7] = _047_ ? (* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:445" *) _041_[7] : 1'hx;
  assign _028_[2] = mux_in_sel_i[2] ^(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  1'h1;
  assign _029_[1] = mux_in_sel_i[1] ^(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  1'h1;
  assign _029_[0] = mux_in_sel_i[0] ^(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  1'h1;
  assign _030_[2] = mux_out_sel_i[2] ^(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  1'h1;
  assign _031_[1] = mux_out_sel_i[1] ^(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  1'h1;
  assign _031_[0] = mux_out_sel_i[0] ^(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15" *)  1'h1;
  assign _040_[32] = data_i[0] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _046_;
  assign _040_[33] = data_i[1] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _046_;
  assign _040_[34] = data_i[2] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _046_;
  assign _040_[35] = data_i[3] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _046_;
  assign _040_[36] = data_i[4] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _046_;
  assign _040_[37] = data_i[5] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _046_;
  assign _040_[38] = data_i[6] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _046_;
  assign _040_[39] = data_i[7] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _046_;
  assign _040_[24] = data_i[8] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _045_;
  assign _040_[25] = data_i[9] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _045_;
  assign _040_[26] = data_i[10] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _045_;
  assign _040_[27] = data_i[11] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _045_;
  assign _040_[28] = data_i[12] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _045_;
  assign _040_[29] = data_i[13] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _045_;
  assign _040_[30] = data_i[14] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _045_;
  assign _040_[31] = data_i[15] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _045_;
  assign _040_[16] = data_i[16] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _044_;
  assign _040_[17] = data_i[17] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _044_;
  assign _040_[18] = data_i[18] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _044_;
  assign _040_[19] = data_i[19] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _044_;
  assign _040_[20] = data_i[20] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _044_;
  assign _040_[21] = data_i[21] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _044_;
  assign _040_[22] = data_i[22] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _044_;
  assign _040_[23] = data_i[23] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _044_;
  assign _040_[8] = data_i[24] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _043_;
  assign _040_[9] = data_i[25] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _043_;
  assign _040_[10] = data_i[26] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _043_;
  assign _040_[11] = data_i[27] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _043_;
  assign _040_[12] = data_i[28] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _043_;
  assign _040_[13] = data_i[29] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _043_;
  assign _040_[14] = data_i[30] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _043_;
  assign _040_[15] = data_i[31] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _043_;
  assign _040_[0] = data_i[32] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _042_;
  assign _040_[1] = data_i[33] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _042_;
  assign _040_[2] = data_i[34] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _042_;
  assign _040_[3] = data_i[35] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _042_;
  assign _040_[4] = data_i[36] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _042_;
  assign _040_[5] = data_i[37] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _042_;
  assign _040_[6] = data_i[38] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _042_;
  assign _040_[7] = data_i[39] &(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15|<techmap.v>:434" *)  _042_;
  assign _028_[1:0] = mux_in_sel_i[1:0];
  assign _029_[2] = mux_in_sel_i[2];
  assign _030_[1:0] = mux_out_sel_i[1:0];
  assign _031_[2] = mux_out_sel_i[2];
  assign data_o = { \mux_out_data_v[4] , \mux_out_data_v[3] , \mux_out_data_v[2] , \mux_out_data_v[1] , \mux_out_data_v[0]  };
  assign i = 32'd5;
  assign \mux_in[0]  = data_i[7:0];
  assign \mux_in[1]  = data_i[15:8];
  assign \mux_in[2]  = data_i[23:16];
  assign \mux_in[3]  = data_i[31:24];
  assign \mux_in[4]  = data_i[39:32];
  assign pckt_in_chosen_o = mux_in_data_chosen_w;
endmodule

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:3" *)
module xy_router(col_addr, row_addr, mux_out_sel_o);
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:106" *)
  wire [2:0] _00_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:106" *)
  wire [2:0] _01_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:106" *)
  wire [2:0] _02_;
  wire [1:0] _03_;
  wire [1:0] _04_;
  wire _05_;
  wire [1:0] _06_;
  wire _07_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2" *)
  wire [3:0] _08_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3" *)
  wire [3:0] _09_;
  wire [3:0] _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2" *)
  wire [3:0] _14_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3" *)
  wire [3:0] _15_;
  wire [3:0] _16_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122|<techmap.v>:260|<techmap.v>:221" *)
  wire _17_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122|<techmap.v>:260|<techmap.v>:221" *)
  wire _18_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122|<techmap.v>:260|<techmap.v>:221" *)
  wire _19_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122|<techmap.v>:260|<techmap.v>:221" *)
  wire _20_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:260|<techmap.v>:221" *)
  wire _21_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:260|<techmap.v>:221" *)
  wire _22_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:260|<techmap.v>:221" *)
  wire _23_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:260|<techmap.v>:222" *)
  wire _24_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:260|<techmap.v>:221" *)
  wire _25_;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:39" *)
  wire [2:0] DOWN;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:36" *)
  wire [2:0] LEFT;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:35" *)
  wire [2:0] RESOURCE;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:38" *)
  wire [2:0] RIGHT;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:37" *)
  wire [2:0] UP;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:13" *)
  input [3:0] col_addr;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:27" *)
  wire [3:0] col_cord;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:15" *)
  output [2:0] mux_out_sel_o;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:24" *)
  wire [2:0] mux_out_sel_w;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:14" *)
  input [3:0] row_addr;
  (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:28" *)
  wire [3:0] row_cord;
  assign _03_[0] = _09_[0] &(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122" *)  _10_[1];
  assign _03_[1] = _10_[2] &(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122" *)  _10_[3];
  assign _12_ = _03_[0] &(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122" *)  _03_[1];
  assign _04_[0] = col_addr[0] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:108" *)  col_addr[1];
  assign _04_[1] = col_addr[2] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:108" *)  col_addr[3];
  assign _05_ = _04_[0] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:108" *)  _04_[1];
  assign _06_[0] = row_addr[0] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:110" *)  row_addr[1];
  assign _06_[1] = row_addr[2] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:110" *)  row_addr[3];
  assign _07_ = _06_[0] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:110" *)  _06_[1];
  assign _02_[1] = ~(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122" *) _13_;
  assign _01_[0] = ~(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114" *) _14_[3];
  assign mux_out_sel_o[0] = _05_ ? (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:108" *) 1'h0 : _00_[0];
  assign mux_out_sel_o[1] = _05_ ? (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:108" *) _02_[1] : 1'h0;
  assign _00_[0] = _07_ ? (* src = "../srcs/switch/simple_mesh_xy/router_xy.v:110" *) _01_[0] : 1'h0;
  assign _11_ = ~(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122" *) _08_[3];
  assign _13_ = _11_ | _12_;
  assign _15_[0] = row_addr[0] ^(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:262" *)  1'h1;
  assign _16_[1] = row_addr[1] ^(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:262" *)  1'h1;
  assign _16_[2] = row_addr[2] ^(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:262" *)  1'h1;
  assign _16_[3] = row_addr[3] ^(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:262" *)  1'h1;
  assign _09_[0] = col_addr[0] ^(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122|<techmap.v>:262" *)  1'h1;
  assign _10_[1] = col_addr[1] ^(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122|<techmap.v>:262" *)  1'h1;
  assign _10_[2] = col_addr[2] ^(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122|<techmap.v>:262" *)  1'h1;
  assign _10_[3] = col_addr[3] ^(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122|<techmap.v>:262" *)  1'h1;
  assign _21_ = _16_[1] &(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:260|<techmap.v>:221" *)  _14_[0];
  assign _22_ = _16_[3] &(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:260|<techmap.v>:221" *)  row_addr[2];
  assign _23_ = _24_ &(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:260|<techmap.v>:221" *)  _14_[1];
  assign _24_ = _16_[3] &(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:260|<techmap.v>:222" *)  _16_[2];
  assign _14_[0] = row_addr[0] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:260|<techmap.v>:212" *)  _15_[0];
  assign _14_[1] = row_addr[1] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:260|<techmap.v>:221" *)  _21_;
  assign _25_ = row_addr[3] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:260|<techmap.v>:221" *)  _22_;
  assign _14_[3] = _25_ |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:114|<techmap.v>:260|<techmap.v>:221" *)  _23_;
  assign _17_ = _10_[1] &(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122|<techmap.v>:260|<techmap.v>:221" *)  _08_[0];
  assign _18_ = _10_[3] &(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122|<techmap.v>:260|<techmap.v>:221" *)  col_addr[2];
  assign _19_ = _03_[1] &(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122|<techmap.v>:260|<techmap.v>:221" *)  _08_[1];
  assign _08_[0] = col_addr[0] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122|<techmap.v>:260|<techmap.v>:212" *)  _09_[0];
  assign _08_[1] = col_addr[1] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122|<techmap.v>:260|<techmap.v>:221" *)  _17_;
  assign _20_ = col_addr[3] |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122|<techmap.v>:260|<techmap.v>:221" *)  _18_;
  assign _08_[3] = _20_ |(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:122|<techmap.v>:260|<techmap.v>:221" *)  _19_;
  assign _00_[2:1] = 2'h0;
  assign _01_[2:1] = 2'h0;
  assign { _02_[2], _02_[0] } = 2'h0;
  assign _10_[0] = _09_[0];
  assign _16_[0] = _15_[0];
  assign DOWN = 3'h0;
  assign LEFT = 3'h0;
  assign RESOURCE = 3'h0;
  assign RIGHT = 3'h2;
  assign UP = 3'h1;
  assign col_cord = 4'h0;
  assign mux_out_sel_o[2] = 1'h0;
  assign mux_out_sel_w = { 1'h0, mux_out_sel_o[1:0] };
  assign row_cord = 4'h0;
endmodule

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:39" *)
module xy_switch(clk_i, rst_ni, wr_en_sw_i, pckt_sw_i, in_fifo_full_o, in_fifo_overflow_o, nxt_fifo_full_i, nxt_fifo_overflow_i, wr_en_sw_o, pckt_sw_o);
  wire [1:0] _00_;
  wire _01_;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *)
  wire _02_;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:54" *)
  input clk_i;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:79" *)
  wire [3:0] col_addr_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:74" *)
  wire [79:0] data_out_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:88" *)
  wire [4:0] empty_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:86" *)
  wire [79:0] fifo_data_out_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:93" *)
  wire [15:0] \genfifo[0].x_pckt_in_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:94" *)
  wire [15:0] \genfifo[0].x_pckt_out_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:93" *)
  wire [15:0] \genfifo[1].x_pckt_in_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:94" *)
  wire [15:0] \genfifo[1].x_pckt_out_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:93" *)
  wire [15:0] \genfifo[2].x_pckt_in_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:94" *)
  wire [15:0] \genfifo[2].x_pckt_out_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:93" *)
  wire [15:0] \genfifo[3].x_pckt_in_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:94" *)
  wire [15:0] \genfifo[3].x_pckt_out_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:93" *)
  wire [15:0] \genfifo[4].x_pckt_in_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:94" *)
  wire [15:0] \genfifo[4].x_pckt_out_w ;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:60" *)
  output [4:0] in_fifo_full_o;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:61" *)
  output [4:0] in_fifo_overflow_o;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:72" *)
  wire [2:0] mux_in_sel_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:73" *)
  wire [2:0] mux_out_sel_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:64" *)
  input [4:0] nxt_fifo_full_i;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:65" *)
  input [4:0] nxt_fifo_overflow_i;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:75" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [15:0] pckt_in_chosen_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:59" *)
  input [79:0] pckt_sw_i;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:67" *)
  output [79:0] pckt_sw_o;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:87" *)
  wire [4:0] rd_en_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:78" *)
  wire [3:0] row_addr_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:55" *)
  input rst_ni;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:89" *)
  (* unused_bits = "0 1 2 3 4" *)
  wire [4:0] underflow_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:71" *)
  wire [4:0] vld_input_w;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:58" *)
  input [4:0] wr_en_sw_i;
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:66" *)
  output [4:0] wr_en_sw_o;
  assign _00_[0] = vld_input_w[4] |(* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *)  vld_input_w[3];
  assign _00_[1] = vld_input_w[2] |(* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *)  vld_input_w[1];
  assign _01_ = _00_[0] |(* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *)  _00_[1];
  assign _02_ = _01_ |(* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *)  vld_input_w[0];
  assign pckt_sw_o[0] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[0] : 1'h0;
  assign pckt_sw_o[1] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[1] : 1'h0;
  assign pckt_sw_o[2] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[2] : 1'h0;
  assign pckt_sw_o[3] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[3] : 1'h0;
  assign pckt_sw_o[4] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[4] : 1'h0;
  assign pckt_sw_o[5] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[5] : 1'h0;
  assign pckt_sw_o[6] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[6] : 1'h0;
  assign pckt_sw_o[7] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[7] : 1'h0;
  assign pckt_sw_o[8] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[8] : 1'h0;
  assign pckt_sw_o[9] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[9] : 1'h0;
  assign pckt_sw_o[10] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[10] : 1'h0;
  assign pckt_sw_o[11] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[11] : 1'h0;
  assign pckt_sw_o[12] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[12] : 1'h0;
  assign pckt_sw_o[13] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[13] : 1'h0;
  assign pckt_sw_o[14] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[14] : 1'h0;
  assign pckt_sw_o[15] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[15] : 1'h0;
  assign pckt_sw_o[16] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[16] : 1'h0;
  assign pckt_sw_o[17] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[17] : 1'h0;
  assign pckt_sw_o[18] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[18] : 1'h0;
  assign pckt_sw_o[19] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[19] : 1'h0;
  assign pckt_sw_o[20] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[20] : 1'h0;
  assign pckt_sw_o[21] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[21] : 1'h0;
  assign pckt_sw_o[22] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[22] : 1'h0;
  assign pckt_sw_o[23] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[23] : 1'h0;
  assign pckt_sw_o[24] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[24] : 1'h0;
  assign pckt_sw_o[25] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[25] : 1'h0;
  assign pckt_sw_o[26] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[26] : 1'h0;
  assign pckt_sw_o[27] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[27] : 1'h0;
  assign pckt_sw_o[28] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[28] : 1'h0;
  assign pckt_sw_o[29] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[29] : 1'h0;
  assign pckt_sw_o[30] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[30] : 1'h0;
  assign pckt_sw_o[31] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[31] : 1'h0;
  assign pckt_sw_o[32] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[32] : 1'h0;
  assign pckt_sw_o[33] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[33] : 1'h0;
  assign pckt_sw_o[34] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[34] : 1'h0;
  assign pckt_sw_o[35] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[35] : 1'h0;
  assign pckt_sw_o[36] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[36] : 1'h0;
  assign pckt_sw_o[37] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[37] : 1'h0;
  assign pckt_sw_o[38] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[38] : 1'h0;
  assign pckt_sw_o[39] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[39] : 1'h0;
  assign pckt_sw_o[40] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[40] : 1'h0;
  assign pckt_sw_o[41] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[41] : 1'h0;
  assign pckt_sw_o[42] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[42] : 1'h0;
  assign pckt_sw_o[43] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[43] : 1'h0;
  assign pckt_sw_o[44] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[44] : 1'h0;
  assign pckt_sw_o[45] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[45] : 1'h0;
  assign pckt_sw_o[46] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[46] : 1'h0;
  assign pckt_sw_o[47] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[47] : 1'h0;
  assign pckt_sw_o[48] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[48] : 1'h0;
  assign pckt_sw_o[49] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[49] : 1'h0;
  assign pckt_sw_o[50] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[50] : 1'h0;
  assign pckt_sw_o[51] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[51] : 1'h0;
  assign pckt_sw_o[52] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[52] : 1'h0;
  assign pckt_sw_o[53] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[53] : 1'h0;
  assign pckt_sw_o[54] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[54] : 1'h0;
  assign pckt_sw_o[55] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[55] : 1'h0;
  assign pckt_sw_o[56] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[56] : 1'h0;
  assign pckt_sw_o[57] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[57] : 1'h0;
  assign pckt_sw_o[58] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[58] : 1'h0;
  assign pckt_sw_o[59] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[59] : 1'h0;
  assign pckt_sw_o[60] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[60] : 1'h0;
  assign pckt_sw_o[61] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[61] : 1'h0;
  assign pckt_sw_o[62] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[62] : 1'h0;
  assign pckt_sw_o[63] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[63] : 1'h0;
  assign pckt_sw_o[64] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[64] : 1'h0;
  assign pckt_sw_o[65] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[65] : 1'h0;
  assign pckt_sw_o[66] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[66] : 1'h0;
  assign pckt_sw_o[67] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[67] : 1'h0;
  assign pckt_sw_o[68] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[68] : 1'h0;
  assign pckt_sw_o[69] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[69] : 1'h0;
  assign pckt_sw_o[70] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[70] : 1'h0;
  assign pckt_sw_o[71] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[71] : 1'h0;
  assign pckt_sw_o[72] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[72] : 1'h0;
  assign pckt_sw_o[73] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[73] : 1'h0;
  assign pckt_sw_o[74] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[74] : 1'h0;
  assign pckt_sw_o[75] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[75] : 1'h0;
  assign pckt_sw_o[76] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[76] : 1'h0;
  assign pckt_sw_o[77] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[77] : 1'h0;
  assign pckt_sw_o[78] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[78] : 1'h0;
  assign pckt_sw_o[79] = _02_ ? (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:183" *) data_out_w[79] : 1'h0;
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:121" *)
  arbiter #(
    .PORT_N(32'sd5)
  ) arb (
    .mux_in_sel_o(mux_in_sel_w),
    .vld_input_i(vld_input_w)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:149" *)
  control_unit #(
    .PORT_N(32'sd5)
  ) control_u (
    .clk_i(clk_i),
    .empty_i(empty_w),
    .full_i(nxt_fifo_full_i),
    .mux_in_sel_i(mux_in_sel_w),
    .mux_out_sel_i(mux_out_sel_w),
    .rd_en_o(rd_en_w),
    .rst_ni(rst_ni),
    .vld_input_o(vld_input_w),
    .wr_en_o(wr_en_sw_o)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:167" *)
  n_to_n_crossbar #(
    .DATA_WIDTH(32'sd16),
    .PORT_N(32'sd5)
  ) crossbar (
    .clk_i(clk_i),
    .data_i({ \genfifo[4].x_pckt_out_w , \genfifo[3].x_pckt_out_w , \genfifo[2].x_pckt_out_w , \genfifo[1].x_pckt_out_w , \genfifo[0].x_pckt_out_w  }),
    .data_o(data_out_w),
    .mux_in_sel_i(mux_in_sel_w),
    .mux_out_sel_i(mux_out_sel_w),
    .pckt_in_chosen_o(pckt_in_chosen_w),
    .rst_ni(rst_ni)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:96" *)
  fifo #(
    .DATA_WIDTH(32'sd16),
    .FIFO_DEPTH_WIDTH(32'sd3),
    .ID(32'sd0)
  ) \genfifo[0].x_input_fifo  (
    .clk_i(clk_i),
    .data_i(pckt_sw_i[15:0]),
    .data_o(\genfifo[0].x_pckt_out_w ),
    .empty_o(empty_w[0]),
    .full_o(in_fifo_full_o[0]),
    .overflow_o(in_fifo_overflow_o[0]),
    .rd_en_i(rd_en_w[0]),
    .rst_ni(rst_ni),
    .underflow_o(underflow_w[0]),
    .wr_en_i(wr_en_sw_i[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:96" *)
  fifo #(
    .DATA_WIDTH(32'sd16),
    .FIFO_DEPTH_WIDTH(32'sd3),
    .ID(32'sd1)
  ) \genfifo[1].x_input_fifo  (
    .clk_i(clk_i),
    .data_i(pckt_sw_i[31:16]),
    .data_o(\genfifo[1].x_pckt_out_w ),
    .empty_o(empty_w[1]),
    .full_o(in_fifo_full_o[1]),
    .overflow_o(in_fifo_overflow_o[1]),
    .rd_en_i(rd_en_w[1]),
    .rst_ni(rst_ni),
    .underflow_o(underflow_w[1]),
    .wr_en_i(wr_en_sw_i[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:96" *)
  fifo #(
    .DATA_WIDTH(32'sd16),
    .FIFO_DEPTH_WIDTH(32'sd3),
    .ID(32'sd2)
  ) \genfifo[2].x_input_fifo  (
    .clk_i(clk_i),
    .data_i(pckt_sw_i[47:32]),
    .data_o(\genfifo[2].x_pckt_out_w ),
    .empty_o(empty_w[2]),
    .full_o(in_fifo_full_o[2]),
    .overflow_o(in_fifo_overflow_o[2]),
    .rd_en_i(rd_en_w[2]),
    .rst_ni(rst_ni),
    .underflow_o(underflow_w[2]),
    .wr_en_i(wr_en_sw_i[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:96" *)
  fifo #(
    .DATA_WIDTH(32'sd16),
    .FIFO_DEPTH_WIDTH(32'sd3),
    .ID(32'sd3)
  ) \genfifo[3].x_input_fifo  (
    .clk_i(clk_i),
    .data_i(pckt_sw_i[63:48]),
    .data_o(\genfifo[3].x_pckt_out_w ),
    .empty_o(empty_w[3]),
    .full_o(in_fifo_full_o[3]),
    .overflow_o(in_fifo_overflow_o[3]),
    .rd_en_i(rd_en_w[3]),
    .rst_ni(rst_ni),
    .underflow_o(underflow_w[3]),
    .wr_en_i(wr_en_sw_i[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:96" *)
  fifo #(
    .DATA_WIDTH(32'sd16),
    .FIFO_DEPTH_WIDTH(32'sd3),
    .ID(32'sd4)
  ) \genfifo[4].x_input_fifo  (
    .clk_i(clk_i),
    .data_i(pckt_sw_i[79:64]),
    .data_o(\genfifo[4].x_pckt_out_w ),
    .empty_o(empty_w[4]),
    .full_o(in_fifo_full_o[4]),
    .overflow_o(in_fifo_overflow_o[4]),
    .rd_en_i(rd_en_w[4]),
    .rst_ni(rst_ni),
    .underflow_o(underflow_w[4]),
    .wr_en_i(wr_en_sw_i[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:132" *)
  xy_router #(
    .COL_CORD(32'sd0),
    .OUTPUT_N_W(32'sd3),
    .PACKET_ADDR_COL_W(32'sd4),
    .PACKET_ADDR_ROW_W(32'sd4),
    .ROW_CORD(32'sd0),
    .SW_CONFIG(32'sd0)
  ) router (
    .col_addr(pckt_in_chosen_w[11:8]),
    .mux_out_sel_o(mux_out_sel_w),
    .row_addr(pckt_in_chosen_w[15:12])
  );
  assign col_addr_w = pckt_in_chosen_w[11:8];
  assign fifo_data_out_w = { \genfifo[4].x_pckt_out_w , \genfifo[3].x_pckt_out_w , \genfifo[2].x_pckt_out_w , \genfifo[1].x_pckt_out_w , \genfifo[0].x_pckt_out_w  };
  assign \genfifo[0].x_pckt_in_w  = pckt_sw_i[15:0];
  assign \genfifo[1].x_pckt_in_w  = pckt_sw_i[31:16];
  assign \genfifo[2].x_pckt_in_w  = pckt_sw_i[47:32];
  assign \genfifo[3].x_pckt_in_w  = pckt_sw_i[63:48];
  assign \genfifo[4].x_pckt_in_w  = pckt_sw_i[79:64];
  assign row_addr_w = pckt_in_chosen_w[15:12];
endmodule
