/* Generated by Yosys 0.9+3981 (git sha1 375af199, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "../srcs/components/fifo.v:6.1-134.10" *)
module fifo(clk_i, rst_ni, wr_en_i, rd_en_i, data_i, data_o, full_o, empty_o, overflow_o, underflow_o);
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  wire _000_;
  (* src = "../srcs/components/fifo.v:71.5-93.8" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire [1:0] _011_;
  wire [1:0] _012_;
  wire [1:0] _013_;
  wire [1:0] _014_;
  wire [1:0] _015_;
  wire [1:0] _016_;
  wire [1:0] _017_;
  wire [1:0] _018_;
  wire [1:0] _019_;
  wire _020_;
  wire _021_;
  wire [1:0] _022_;
  wire [1:0] _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  (* src = "../srcs/components/fifo.v:54.15-54.33" *)
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  (* force_downto = 32'd1 *)
  (* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [31:0] _037_;
  (* force_downto = 32'd1 *)
  (* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [3:0] _038_;
  (* force_downto = 32'd1 *)
  (* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [7:0] _039_;
  (* force_downto = 32'd1 *)
  (* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [7:0] _040_;
  (* force_downto = 32'd1 *)
  (* src = "../srcs/components/fifo.v:56.34-56.49|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [1:0] _041_;
  (* force_downto = 32'd1 *)
  (* src = "../srcs/components/fifo.v:56.34-56.49|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [1:0] _042_;
  (* force_downto = 32'd1 *)
  (* src = "../srcs/components/fifo.v:81.28-81.43|../srcs/components/fifo.v:56.34-56.49|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [1:0] _043_;
  (* force_downto = 32'd1 *)
  (* src = "../srcs/components/fifo.v:81.28-81.43|../srcs/components/fifo.v:56.34-56.49|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [1:0] _044_;
  (* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _045_;
  (* src = "../srcs/components/fifo.v:13.11-13.16" *)
  input clk_i;
  (* src = "../srcs/components/fifo.v:17.30-17.36" *)
  input [7:0] data_i;
  (* src = "../srcs/components/fifo.v:18.31-18.37" *)
  output [7:0] data_o;
  (* src = "../srcs/components/fifo.v:33.28-33.34" *)
  reg [7:0] data_v;
  (* src = "../srcs/components/fifo.v:20.12-20.19" *)
  output empty_o;
  (* src = "../srcs/components/fifo.v:39.18-39.25" *)
  wire empty_w;
  (* src = "../srcs/components/fifo.v:34.28-34.34" *)
  reg [7:0] \fifo_v[0] ;
  (* src = "../srcs/components/fifo.v:34.28-34.34" *)
  reg [7:0] \fifo_v[1] ;
  (* src = "../srcs/components/fifo.v:34.28-34.34" *)
  reg [7:0] \fifo_v[2] ;
  (* src = "../srcs/components/fifo.v:34.28-34.34" *)
  reg [7:0] \fifo_v[3] ;
  (* src = "../srcs/components/fifo.v:19.12-19.18" *)
  output full_o;
  (* src = "../srcs/components/fifo.v:39.10-39.16" *)
  wire full_w;
  (* src = "../srcs/components/fifo.v:21.12-21.22" *)
  output overflow_o;
  (* src = "../srcs/components/fifo.v:36.9-36.19" *)
  reg overflow_v;
  (* src = "../srcs/components/fifo.v:16.11-16.18" *)
  input rd_en_i;
  (* src = "../srcs/components/fifo.v:35.44-35.52" *)
  reg [1:0] rd_ptr_v;
  (* src = "../srcs/components/fifo.v:14.11-14.17" *)
  input rst_ni;
  (* src = "../srcs/components/fifo.v:22.12-22.23" *)
  output underflow_o;
  (* src = "../srcs/components/fifo.v:36.21-36.32" *)
  reg underflow_v;
  (* src = "../srcs/components/fifo.v:15.11-15.18" *)
  input wr_en_i;
  (* src = "../srcs/components/fifo.v:35.34-35.42" *)
  reg [1:0] wr_ptr_v;
  assign _041_[0] = ~wr_ptr_v[0];
  assign _010_ = ~rd_ptr_v[1];
  assign _043_[0] = ~rd_ptr_v[0];
  assign _009_ = ~wr_ptr_v[1];
  assign _024_ = _022_[0] |(* src = "../srcs/components/fifo.v:40.24-40.51" *)  _022_[1];
  assign _008_ = _023_[0] |(* src = "../srcs/components/fifo.v:41.24-41.44" *)  _023_[1];
  assign _004_ = _006_ & _034_;
  assign _005_ = _006_ & _035_;
  assign _002_ = _006_ & _032_;
  assign _025_ = _043_[0] |(* src = "../srcs/components/fifo.v:0.0-0.0" *)  _010_;
  assign _026_ = rd_ptr_v[0] |(* src = "../srcs/components/fifo.v:0.0-0.0" *)  _010_;
  assign _027_ = _043_[0] |(* src = "../srcs/components/fifo.v:0.0-0.0" *)  rd_ptr_v[1];
  assign _006_ = wr_en_i & _031_;
  assign _003_ = _006_ & _033_;
  assign _028_ = _041_[0] |(* src = "../srcs/components/fifo.v:0.0-0.0" *)  _009_;
  assign _029_ = wr_ptr_v[0] |(* src = "../srcs/components/fifo.v:0.0-0.0" *)  _009_;
  assign _030_ = _041_[0] |(* src = "../srcs/components/fifo.v:0.0-0.0" *)  wr_ptr_v[1];
  assign _007_ = rd_en_i & _008_;
  assign _011_[0] = _037_[7] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _037_[15];
  assign _011_[1] = _037_[23] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _037_[31];
  assign _040_[7] = _011_[0] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _011_[1];
  assign _012_[0] = _037_[6] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _037_[14];
  assign _012_[1] = _037_[22] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _037_[30];
  assign _040_[6] = _012_[0] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _012_[1];
  assign _013_[0] = _037_[5] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _037_[13];
  assign _013_[1] = _037_[21] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _037_[29];
  assign _040_[5] = _013_[0] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _013_[1];
  assign _014_[0] = _037_[4] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _037_[12];
  assign _014_[1] = _037_[20] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _037_[28];
  assign _040_[4] = _014_[0] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _014_[1];
  assign _015_[0] = _037_[3] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _037_[11];
  assign _015_[1] = _037_[19] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _037_[27];
  assign _040_[3] = _015_[0] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _015_[1];
  assign _016_[0] = _037_[2] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _037_[10];
  assign _016_[1] = _037_[18] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _037_[26];
  assign _040_[2] = _016_[0] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _016_[1];
  assign _017_[0] = _037_[1] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _037_[9];
  assign _017_[1] = _037_[17] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _037_[25];
  assign _040_[1] = _017_[0] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _017_[1];
  assign _018_[0] = _037_[0] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _037_[8];
  assign _018_[1] = _037_[16] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _037_[24];
  assign _040_[0] = _018_[0] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _018_[1];
  assign _019_[0] = _038_[0] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)  _038_[1];
  assign _019_[1] = _038_[2] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)  _038_[3];
  assign _045_ = _019_[0] |(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)  _019_[1];
  assign _020_ = rd_ptr_v[0] |(* src = "../srcs/components/fifo.v:0.0-0.0" *)  rd_ptr_v[1];
  assign _021_ = wr_ptr_v[0] |(* src = "../srcs/components/fifo.v:0.0-0.0" *)  wr_ptr_v[1];
  assign full_o = ~(* src = "../srcs/components/fifo.v:40.24-40.51" *) _024_;
  assign empty_o = ~(* src = "../srcs/components/fifo.v:41.24-41.44" *) _008_;
  assign _038_[0] = ~(* src = "../srcs/components/fifo.v:0.0-0.0" *) _025_;
  assign _038_[1] = ~(* src = "../srcs/components/fifo.v:0.0-0.0" *) _026_;
  assign _038_[2] = ~(* src = "../srcs/components/fifo.v:0.0-0.0" *) _027_;
  assign _038_[3] = ~(* src = "../srcs/components/fifo.v:0.0-0.0" *) _020_;
  assign _032_ = ~(* src = "../srcs/components/fifo.v:0.0-0.0" *) _028_;
  assign _033_ = ~(* src = "../srcs/components/fifo.v:0.0-0.0" *) _029_;
  assign _034_ = ~(* src = "../srcs/components/fifo.v:0.0-0.0" *) _030_;
  assign _035_ = ~(* src = "../srcs/components/fifo.v:0.0-0.0" *) _021_;
  assign _031_ = _024_ |(* src = "../srcs/components/fifo.v:54.15-54.33" *)  rd_en_i;
  assign underflow_o = _008_ ? (* src = "../srcs/components/fifo.v:90.15-90.23|../srcs/components/fifo.v:90.11-90.45" *) 1'h0 : underflow_v;
  assign _001_ = rd_en_i ? (* src = "../srcs/components/fifo.v:78.13-78.20|../srcs/components/fifo.v:78.9-91.12" *) empty_o : underflow_o;
  assign overflow_o = _024_ ? (* src = "../srcs/components/fifo.v:65.15-65.22|../srcs/components/fifo.v:65.11-65.43" *) 1'h0 : overflow_v;
  assign _036_ = ~(* src = "../srcs/components/fifo.v:54.15-54.33|../srcs/components/fifo.v:54.11-62.14" *) _031_;
  assign _000_ = wr_en_i ? (* src = "../srcs/components/fifo.v:53.13-53.20|../srcs/components/fifo.v:53.9-66.12" *) _036_ : overflow_o;
  assign _039_[0] = _045_ ? (* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _040_[0] : 1'hx;
  assign _039_[1] = _045_ ? (* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _040_[1] : 1'hx;
  assign _039_[2] = _045_ ? (* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _040_[2] : 1'hx;
  assign _039_[3] = _045_ ? (* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _040_[3] : 1'hx;
  assign _039_[4] = _045_ ? (* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _040_[4] : 1'hx;
  assign _039_[5] = _045_ ? (* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _040_[5] : 1'hx;
  assign _039_[6] = _045_ ? (* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _040_[6] : 1'hx;
  assign _039_[7] = _045_ ? (* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _040_[7] : 1'hx;
  (* src = "../srcs/components/fifo.v:71.5-93.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) underflow_v <= 1'h0;
    else underflow_v <= _001_;
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) overflow_v <= 1'h0;
    else overflow_v <= _000_;
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[1] [0] <= 1'h0;
    else if (_004_) \fifo_v[1] [0] <= data_i[0];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[1] [1] <= 1'h0;
    else if (_004_) \fifo_v[1] [1] <= data_i[1];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[1] [2] <= 1'h0;
    else if (_004_) \fifo_v[1] [2] <= data_i[2];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[1] [3] <= 1'h0;
    else if (_004_) \fifo_v[1] [3] <= data_i[3];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[1] [4] <= 1'h0;
    else if (_004_) \fifo_v[1] [4] <= data_i[4];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[1] [5] <= 1'h0;
    else if (_004_) \fifo_v[1] [5] <= data_i[5];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[1] [6] <= 1'h0;
    else if (_004_) \fifo_v[1] [6] <= data_i[6];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[1] [7] <= 1'h0;
    else if (_004_) \fifo_v[1] [7] <= data_i[7];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[2] [0] <= 1'h0;
    else if (_003_) \fifo_v[2] [0] <= data_i[0];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[2] [1] <= 1'h0;
    else if (_003_) \fifo_v[2] [1] <= data_i[1];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[2] [2] <= 1'h0;
    else if (_003_) \fifo_v[2] [2] <= data_i[2];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[2] [3] <= 1'h0;
    else if (_003_) \fifo_v[2] [3] <= data_i[3];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[2] [4] <= 1'h0;
    else if (_003_) \fifo_v[2] [4] <= data_i[4];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[2] [5] <= 1'h0;
    else if (_003_) \fifo_v[2] [5] <= data_i[5];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[2] [6] <= 1'h0;
    else if (_003_) \fifo_v[2] [6] <= data_i[6];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[2] [7] <= 1'h0;
    else if (_003_) \fifo_v[2] [7] <= data_i[7];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[0] [0] <= 1'h0;
    else if (_005_) \fifo_v[0] [0] <= data_i[0];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[0] [1] <= 1'h0;
    else if (_005_) \fifo_v[0] [1] <= data_i[1];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[0] [2] <= 1'h0;
    else if (_005_) \fifo_v[0] [2] <= data_i[2];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[0] [3] <= 1'h0;
    else if (_005_) \fifo_v[0] [3] <= data_i[3];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[0] [4] <= 1'h0;
    else if (_005_) \fifo_v[0] [4] <= data_i[4];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[0] [5] <= 1'h0;
    else if (_005_) \fifo_v[0] [5] <= data_i[5];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[0] [6] <= 1'h0;
    else if (_005_) \fifo_v[0] [6] <= data_i[6];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[0] [7] <= 1'h0;
    else if (_005_) \fifo_v[0] [7] <= data_i[7];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[3] [0] <= 1'h0;
    else if (_002_) \fifo_v[3] [0] <= data_i[0];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[3] [1] <= 1'h0;
    else if (_002_) \fifo_v[3] [1] <= data_i[1];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[3] [2] <= 1'h0;
    else if (_002_) \fifo_v[3] [2] <= data_i[2];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[3] [3] <= 1'h0;
    else if (_002_) \fifo_v[3] [3] <= data_i[3];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[3] [4] <= 1'h0;
    else if (_002_) \fifo_v[3] [4] <= data_i[4];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[3] [5] <= 1'h0;
    else if (_002_) \fifo_v[3] [5] <= data_i[5];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[3] [6] <= 1'h0;
    else if (_002_) \fifo_v[3] [6] <= data_i[6];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \fifo_v[3] [7] <= 1'h0;
    else if (_002_) \fifo_v[3] [7] <= data_i[7];
  (* src = "../srcs/components/fifo.v:71.5-93.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) data_v[0] <= 1'h0;
    else if (_007_) data_v[0] <= _039_[0];
  (* src = "../srcs/components/fifo.v:71.5-93.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) data_v[1] <= 1'h0;
    else if (_007_) data_v[1] <= _039_[1];
  (* src = "../srcs/components/fifo.v:71.5-93.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) data_v[2] <= 1'h0;
    else if (_007_) data_v[2] <= _039_[2];
  (* src = "../srcs/components/fifo.v:71.5-93.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) data_v[3] <= 1'h0;
    else if (_007_) data_v[3] <= _039_[3];
  (* src = "../srcs/components/fifo.v:71.5-93.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) data_v[4] <= 1'h0;
    else if (_007_) data_v[4] <= _039_[4];
  (* src = "../srcs/components/fifo.v:71.5-93.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) data_v[5] <= 1'h0;
    else if (_007_) data_v[5] <= _039_[5];
  (* src = "../srcs/components/fifo.v:71.5-93.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) data_v[6] <= 1'h0;
    else if (_007_) data_v[6] <= _039_[6];
  (* src = "../srcs/components/fifo.v:71.5-93.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) data_v[7] <= 1'h0;
    else if (_007_) data_v[7] <= _039_[7];
  (* src = "../srcs/components/fifo.v:71.5-93.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) rd_ptr_v[0] <= 1'h0;
    else if (_007_) rd_ptr_v[0] <= _043_[0];
  (* src = "../srcs/components/fifo.v:71.5-93.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) rd_ptr_v[1] <= 1'h0;
    else if (_007_) rd_ptr_v[1] <= _044_[1];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) wr_ptr_v[0] <= 1'h0;
    else if (_006_) wr_ptr_v[0] <= _041_[0];
  (* src = "../srcs/components/fifo.v:44.5-68.8" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) wr_ptr_v[1] <= 1'h0;
    else if (_006_) wr_ptr_v[1] <= _042_[1];
  assign _022_[0] = _041_[0] ^(* src = "../srcs/components/fifo.v:40.24-40.51" *)  rd_ptr_v[0];
  assign _022_[1] = _042_[1] ^(* src = "../srcs/components/fifo.v:40.24-40.51" *)  rd_ptr_v[1];
  assign _023_[0] = wr_ptr_v[0] ^(* src = "../srcs/components/fifo.v:41.24-41.44" *)  rd_ptr_v[0];
  assign _023_[1] = wr_ptr_v[1] ^(* src = "../srcs/components/fifo.v:41.24-41.44" *)  rd_ptr_v[1];
  assign _037_[24] = \fifo_v[0] [0] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[3];
  assign _037_[25] = \fifo_v[0] [1] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[3];
  assign _037_[26] = \fifo_v[0] [2] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[3];
  assign _037_[27] = \fifo_v[0] [3] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[3];
  assign _037_[28] = \fifo_v[0] [4] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[3];
  assign _037_[29] = \fifo_v[0] [5] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[3];
  assign _037_[30] = \fifo_v[0] [6] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[3];
  assign _037_[31] = \fifo_v[0] [7] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[3];
  assign _037_[16] = \fifo_v[1] [0] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[2];
  assign _037_[17] = \fifo_v[1] [1] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[2];
  assign _037_[18] = \fifo_v[1] [2] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[2];
  assign _037_[19] = \fifo_v[1] [3] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[2];
  assign _037_[20] = \fifo_v[1] [4] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[2];
  assign _037_[21] = \fifo_v[1] [5] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[2];
  assign _037_[22] = \fifo_v[1] [6] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[2];
  assign _037_[23] = \fifo_v[1] [7] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[2];
  assign _037_[8] = \fifo_v[2] [0] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[1];
  assign _037_[9] = \fifo_v[2] [1] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[1];
  assign _037_[10] = \fifo_v[2] [2] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[1];
  assign _037_[11] = \fifo_v[2] [3] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[1];
  assign _037_[12] = \fifo_v[2] [4] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[1];
  assign _037_[13] = \fifo_v[2] [5] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[1];
  assign _037_[14] = \fifo_v[2] [6] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[1];
  assign _037_[15] = \fifo_v[2] [7] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[1];
  assign _037_[0] = \fifo_v[3] [0] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[0];
  assign _037_[1] = \fifo_v[3] [1] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[0];
  assign _037_[2] = \fifo_v[3] [2] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[0];
  assign _037_[3] = \fifo_v[3] [3] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[0];
  assign _037_[4] = \fifo_v[3] [4] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[0];
  assign _037_[5] = \fifo_v[3] [5] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[0];
  assign _037_[6] = \fifo_v[3] [6] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[0];
  assign _037_[7] = \fifo_v[3] [7] &(* src = "../srcs/components/fifo.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _038_[0];
  assign _042_[1] = wr_ptr_v[1] ^(* src = "../srcs/components/fifo.v:56.34-56.49|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  wr_ptr_v[0];
  assign _044_[1] = rd_ptr_v[1] ^(* src = "../srcs/components/fifo.v:81.28-81.43|../srcs/components/fifo.v:56.34-56.49|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  rd_ptr_v[0];
  assign _041_[1] = wr_ptr_v[1];
  assign _042_[0] = _041_[0];
  assign _043_[1] = rd_ptr_v[1];
  assign _044_[0] = _043_[0];
  assign data_o = data_v;
  assign empty_w = empty_o;
  assign full_w = full_o;
endmodule
