/* Generated by Yosys 0.9+3981 (git sha1 375af199, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "../srcs/switch/simple_mesh_xy/packet_arbiter.v:1.1-114.10" *)
module \$abstract\arbiter ();
endmodule

(* cells_not_processed =  1  *)
(* src = "../srcs/switch/simple_mesh_xy/control_unit.v:6.1-78.10" *)
module \$abstract\control_unit ();
endmodule

(* cells_not_processed =  1  *)
(* src = "../srcs/components/fifo.v:6.1-128.10" *)
module \$abstract\fifo ();
endmodule

(* cells_not_processed =  1  *)
(* src = "../srcs/switch/simple_mesh_xy/crossbar.v:15.1-69.10" *)
module \$abstract\n_to_n_crossbar ();
endmodule

(* cells_not_processed =  1  *)
(* src = "../srcs/switch/simple_mesh_xy/router_xy.v:3.1-152.10" *)
module \$abstract\xy_router ();
endmodule

(* cells_not_processed =  1  *)
(* src = "../srcs/switch/simple_mesh_xy/xy_switch.v:38.1-184.10" *)
module \$abstract\xy_switch ();
endmodule

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "../srcs/noc/mesh_xy_noc.v:24.1-181.10" *)
module mesh_xy_noc(clk_i, rst_ni, rsc_pckt_i, rsc_wren_i, rsc_full_o, rsc_ovrflw_o, rsc_pckt_o, rsc_wren_o, rsc_full_i, rsc_ovrflw_i);
  (* src = "../srcs/noc/mesh_xy_noc.v:36.13-36.18" *)
  input clk_i;
  (* src = "../srcs/noc/mesh_xy_noc.v:103.47-103.58" *)
  wire [4:0] \genrow[0].gencol[0].x_sw_full_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:104.47-104.58" *)
  wire [4:0] \genrow[0].gencol[0].x_sw_full_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:105.47-105.60" *)
  wire [4:0] \genrow[0].gencol[0].x_sw_ovrflw_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:106.47-106.60" *)
  wire [4:0] \genrow[0].gencol[0].x_sw_ovrflw_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:99.83-99.94" *)
  wire [59:0] \genrow[0].gencol[0].x_sw_pckt_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:100.83-100.94" *)
  wire [59:0] \genrow[0].gencol[0].x_sw_pckt_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:101.47-101.58" *)
  wire [4:0] \genrow[0].gencol[0].x_sw_wren_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:102.47-102.58" *)
  wire [4:0] \genrow[0].gencol[0].x_sw_wren_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:103.47-103.58" *)
  wire [4:0] \genrow[0].gencol[1].x_sw_full_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:104.47-104.58" *)
  wire [4:0] \genrow[0].gencol[1].x_sw_full_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:105.47-105.60" *)
  wire [4:0] \genrow[0].gencol[1].x_sw_ovrflw_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:106.47-106.60" *)
  wire [4:0] \genrow[0].gencol[1].x_sw_ovrflw_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:99.83-99.94" *)
  wire [59:0] \genrow[0].gencol[1].x_sw_pckt_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:100.83-100.94" *)
  wire [59:0] \genrow[0].gencol[1].x_sw_pckt_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:101.47-101.58" *)
  wire [4:0] \genrow[0].gencol[1].x_sw_wren_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:102.47-102.58" *)
  wire [4:0] \genrow[0].gencol[1].x_sw_wren_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:103.47-103.58" *)
  wire [4:0] \genrow[0].gencol[2].x_sw_full_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:104.47-104.58" *)
  wire [4:0] \genrow[0].gencol[2].x_sw_full_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:105.47-105.60" *)
  wire [4:0] \genrow[0].gencol[2].x_sw_ovrflw_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:106.47-106.60" *)
  wire [4:0] \genrow[0].gencol[2].x_sw_ovrflw_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:99.83-99.94" *)
  wire [59:0] \genrow[0].gencol[2].x_sw_pckt_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:100.83-100.94" *)
  wire [59:0] \genrow[0].gencol[2].x_sw_pckt_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:101.47-101.58" *)
  wire [4:0] \genrow[0].gencol[2].x_sw_wren_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:102.47-102.58" *)
  wire [4:0] \genrow[0].gencol[2].x_sw_wren_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:103.47-103.58" *)
  wire [4:0] \genrow[1].gencol[0].x_sw_full_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:104.47-104.58" *)
  wire [4:0] \genrow[1].gencol[0].x_sw_full_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:105.47-105.60" *)
  wire [4:0] \genrow[1].gencol[0].x_sw_ovrflw_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:106.47-106.60" *)
  wire [4:0] \genrow[1].gencol[0].x_sw_ovrflw_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:99.83-99.94" *)
  wire [59:0] \genrow[1].gencol[0].x_sw_pckt_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:100.83-100.94" *)
  wire [59:0] \genrow[1].gencol[0].x_sw_pckt_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:101.47-101.58" *)
  wire [4:0] \genrow[1].gencol[0].x_sw_wren_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:102.47-102.58" *)
  wire [4:0] \genrow[1].gencol[0].x_sw_wren_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:103.47-103.58" *)
  wire [4:0] \genrow[1].gencol[1].x_sw_full_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:104.47-104.58" *)
  wire [4:0] \genrow[1].gencol[1].x_sw_full_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:105.47-105.60" *)
  wire [4:0] \genrow[1].gencol[1].x_sw_ovrflw_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:106.47-106.60" *)
  wire [4:0] \genrow[1].gencol[1].x_sw_ovrflw_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:99.83-99.94" *)
  wire [59:0] \genrow[1].gencol[1].x_sw_pckt_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:100.83-100.94" *)
  wire [59:0] \genrow[1].gencol[1].x_sw_pckt_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:101.47-101.58" *)
  wire [4:0] \genrow[1].gencol[1].x_sw_wren_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:102.47-102.58" *)
  wire [4:0] \genrow[1].gencol[1].x_sw_wren_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:103.47-103.58" *)
  wire [4:0] \genrow[1].gencol[2].x_sw_full_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:104.47-104.58" *)
  wire [4:0] \genrow[1].gencol[2].x_sw_full_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:105.47-105.60" *)
  wire [4:0] \genrow[1].gencol[2].x_sw_ovrflw_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:106.47-106.60" *)
  wire [4:0] \genrow[1].gencol[2].x_sw_ovrflw_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:99.83-99.94" *)
  wire [59:0] \genrow[1].gencol[2].x_sw_pckt_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:100.83-100.94" *)
  wire [59:0] \genrow[1].gencol[2].x_sw_pckt_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:101.47-101.58" *)
  wire [4:0] \genrow[1].gencol[2].x_sw_wren_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:102.47-102.58" *)
  wire [4:0] \genrow[1].gencol[2].x_sw_wren_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:103.47-103.58" *)
  wire [4:0] \genrow[2].gencol[0].x_sw_full_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:104.47-104.58" *)
  wire [4:0] \genrow[2].gencol[0].x_sw_full_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:105.47-105.60" *)
  wire [4:0] \genrow[2].gencol[0].x_sw_ovrflw_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:106.47-106.60" *)
  wire [4:0] \genrow[2].gencol[0].x_sw_ovrflw_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:99.83-99.94" *)
  wire [59:0] \genrow[2].gencol[0].x_sw_pckt_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:100.83-100.94" *)
  wire [59:0] \genrow[2].gencol[0].x_sw_pckt_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:101.47-101.58" *)
  wire [4:0] \genrow[2].gencol[0].x_sw_wren_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:102.47-102.58" *)
  wire [4:0] \genrow[2].gencol[0].x_sw_wren_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:103.47-103.58" *)
  wire [4:0] \genrow[2].gencol[1].x_sw_full_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:104.47-104.58" *)
  wire [4:0] \genrow[2].gencol[1].x_sw_full_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:105.47-105.60" *)
  wire [4:0] \genrow[2].gencol[1].x_sw_ovrflw_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:106.47-106.60" *)
  wire [4:0] \genrow[2].gencol[1].x_sw_ovrflw_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:99.83-99.94" *)
  wire [59:0] \genrow[2].gencol[1].x_sw_pckt_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:100.83-100.94" *)
  wire [59:0] \genrow[2].gencol[1].x_sw_pckt_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:101.47-101.58" *)
  wire [4:0] \genrow[2].gencol[1].x_sw_wren_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:102.47-102.58" *)
  wire [4:0] \genrow[2].gencol[1].x_sw_wren_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:103.47-103.58" *)
  wire [4:0] \genrow[2].gencol[2].x_sw_full_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:104.47-104.58" *)
  wire [4:0] \genrow[2].gencol[2].x_sw_full_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:105.47-105.60" *)
  wire [4:0] \genrow[2].gencol[2].x_sw_ovrflw_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:106.47-106.60" *)
  wire [4:0] \genrow[2].gencol[2].x_sw_ovrflw_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:99.83-99.94" *)
  wire [59:0] \genrow[2].gencol[2].x_sw_pckt_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:100.83-100.94" *)
  wire [59:0] \genrow[2].gencol[2].x_sw_pckt_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:101.47-101.58" *)
  wire [4:0] \genrow[2].gencol[2].x_sw_wren_i ;
  (* src = "../srcs/noc/mesh_xy_noc.v:102.47-102.58" *)
  wire [4:0] \genrow[2].gencol[2].x_sw_wren_o ;
  (* src = "../srcs/noc/mesh_xy_noc.v:48.41-48.51" *)
  input [8:0] rsc_full_i;
  (* src = "../srcs/noc/mesh_xy_noc.v:42.41-42.51" *)
  output [8:0] rsc_full_o;
  (* src = "../srcs/noc/mesh_xy_noc.v:49.41-49.53" *)
  input [8:0] rsc_ovrflw_i;
  (* src = "../srcs/noc/mesh_xy_noc.v:43.41-43.53" *)
  output [8:0] rsc_ovrflw_o;
  (* src = "../srcs/noc/mesh_xy_noc.v:40.97-40.107" *)
  input [107:0] rsc_pckt_i;
  (* src = "../srcs/noc/mesh_xy_noc.v:46.97-46.107" *)
  output [107:0] rsc_pckt_o;
  (* src = "../srcs/noc/mesh_xy_noc.v:41.41-41.51" *)
  input [8:0] rsc_wren_i;
  (* src = "../srcs/noc/mesh_xy_noc.v:47.41-47.51" *)
  output [8:0] rsc_wren_o;
  (* src = "../srcs/noc/mesh_xy_noc.v:37.13-37.19" *)
  input rst_ni;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[0] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[10] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[11] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[12] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[13] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[14] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[15] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[16] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[17] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[18] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[19] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[1] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[20] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[21] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[22] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[23] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[24] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[25] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[26] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[27] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[28] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[29] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[2] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[30] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[31] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[32] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[33] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[34] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[35] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[3] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[4] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[5] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[6] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[7] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[8] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:88.31-88.40" *)
  wire \sw_full_w[9] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[0] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[10] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[11] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[12] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[13] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[14] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[15] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[16] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[17] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[18] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[19] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[1] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[20] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[21] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[22] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[23] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[24] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[25] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[26] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[27] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[28] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[29] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[2] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[30] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[31] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[32] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[33] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[34] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[35] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[3] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[4] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[5] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[6] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[7] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[8] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:89.31-89.42" *)
  wire \sw_ovrflw_w[9] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[0] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[10] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[11] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[12] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[13] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[14] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[15] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[16] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[17] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[18] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[19] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[1] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[20] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[21] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[22] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[23] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[24] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[25] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[26] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[27] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[28] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[29] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[2] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[30] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[31] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[32] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[33] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[34] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[35] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[3] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[4] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[5] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[6] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[7] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[8] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:86.67-86.76" *)
  wire [11:0] \sw_pckt_w[9] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[0] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[10] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[11] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[12] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[13] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[14] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[15] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[16] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[17] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[18] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[19] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[1] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[20] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[21] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[22] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[23] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[24] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[25] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[26] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[27] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[28] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[29] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[2] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[30] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[31] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[32] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[33] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[34] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[35] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[3] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[4] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[5] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[6] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[7] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[8] ;
  (* src = "../srcs/noc/mesh_xy_noc.v:87.31-87.40" *)
  wire \sw_wren_w[9] ;
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/noc/mesh_xy_noc.v:145.11-157.14" *)
  xy_switch #(
    .IN_FIFO_DEPTH_W(32'sd3),
    .PCKT_DATA_W(32'sd8),
    .PCKT_W(32'sd12),
    .PCKT_XADDR_W(32'sd2),
    .PCKT_YADDR_W(32'sd2),
    .PORT_N(3'h5),
    .SW_CONFIG(32'sd0),
    .X_CORD(32'sd0),
    .Y_CORD(32'sd0)
  ) \genrow[0].gencol[0].x_sw  (
    .clk_i(clk_i),
    .in_fifo_full_o({ \genrow[0].gencol[0].x_sw_full_o [4:1], rsc_full_i[0] }),
    .in_fifo_overflow_o({ \genrow[0].gencol[0].x_sw_ovrflw_o [4:1], rsc_ovrflw_i[0] }),
    .nxt_fifo_full_i({ \genrow[0].gencol[0].x_sw_full_i [4:3], 2'h0, \genrow[0].gencol[0].x_sw_full_i [0] }),
    .nxt_fifo_overflow_i({ \genrow[0].gencol[0].x_sw_ovrflw_i [4:3], 2'h0, \genrow[0].gencol[0].x_sw_ovrflw_i [0] }),
    .pckt_sw_i({ \genrow[0].gencol[0].x_sw_pckt_i [59:36], 24'h000000, \genrow[0].gencol[0].x_sw_pckt_i [11:0] }),
    .pckt_sw_o({ \genrow[0].gencol[0].x_sw_pckt_o [59:12], rsc_pckt_i[11:0] }),
    .rst_ni(rst_ni),
    .wr_en_sw_i({ \genrow[0].gencol[0].x_sw_wren_i [4:3], 2'h0, \genrow[0].gencol[0].x_sw_wren_i [0] }),
    .wr_en_sw_o({ \genrow[0].gencol[0].x_sw_wren_o [4:1], rsc_wren_i[0] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/noc/mesh_xy_noc.v:145.11-157.14" *)
  xy_switch #(
    .IN_FIFO_DEPTH_W(32'sd3),
    .PCKT_DATA_W(32'sd8),
    .PCKT_W(32'sd12),
    .PCKT_XADDR_W(32'sd2),
    .PCKT_YADDR_W(32'sd2),
    .PORT_N(3'h5),
    .SW_CONFIG(32'sd0),
    .X_CORD(32'sd0),
    .Y_CORD(32'sd1)
  ) \genrow[0].gencol[1].x_sw  (
    .clk_i(clk_i),
    .in_fifo_full_o({ \genrow[0].gencol[1].x_sw_full_o [4:2], \genrow[0].gencol[0].x_sw_full_i [3], rsc_full_i[1] }),
    .in_fifo_overflow_o({ \genrow[0].gencol[1].x_sw_ovrflw_o [4:2], \genrow[0].gencol[0].x_sw_ovrflw_i [3], rsc_ovrflw_i[1] }),
    .nxt_fifo_full_i({ \genrow[0].gencol[1].x_sw_full_i [4:3], 1'h0, \genrow[0].gencol[0].x_sw_full_o [3], \genrow[0].gencol[1].x_sw_full_i [0] }),
    .nxt_fifo_overflow_i({ \genrow[0].gencol[1].x_sw_ovrflw_i [4:3], 1'h0, \genrow[0].gencol[0].x_sw_ovrflw_o [3], \genrow[0].gencol[1].x_sw_ovrflw_i [0] }),
    .pckt_sw_i({ \genrow[0].gencol[1].x_sw_pckt_i [59:36], 12'h000, \genrow[0].gencol[0].x_sw_pckt_o [47:36], \genrow[0].gencol[1].x_sw_pckt_i [11:0] }),
    .pckt_sw_o({ \genrow[0].gencol[1].x_sw_pckt_o [59:24], \genrow[0].gencol[0].x_sw_pckt_i [47:36], rsc_pckt_i[23:12] }),
    .rst_ni(rst_ni),
    .wr_en_sw_i({ \genrow[0].gencol[1].x_sw_wren_i [4:3], 1'h0, \genrow[0].gencol[0].x_sw_wren_o [3], \genrow[0].gencol[1].x_sw_wren_i [0] }),
    .wr_en_sw_o({ \genrow[0].gencol[1].x_sw_wren_o [4:2], \genrow[0].gencol[0].x_sw_wren_i [3], rsc_wren_i[1] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/noc/mesh_xy_noc.v:145.11-157.14" *)
  xy_switch #(
    .IN_FIFO_DEPTH_W(32'sd3),
    .PCKT_DATA_W(32'sd8),
    .PCKT_W(32'sd12),
    .PCKT_XADDR_W(32'sd2),
    .PCKT_YADDR_W(32'sd2),
    .PORT_N(3'h5),
    .SW_CONFIG(32'sd0),
    .X_CORD(32'sd0),
    .Y_CORD(32'sd2)
  ) \genrow[0].gencol[2].x_sw  (
    .clk_i(clk_i),
    .in_fifo_full_o({ \genrow[0].gencol[2].x_sw_full_o [4:2], \genrow[0].gencol[1].x_sw_full_i [3], rsc_full_i[2] }),
    .in_fifo_overflow_o({ \genrow[0].gencol[2].x_sw_ovrflw_o [4:2], \genrow[0].gencol[1].x_sw_ovrflw_i [3], rsc_ovrflw_i[2] }),
    .nxt_fifo_full_i({ \genrow[0].gencol[2].x_sw_full_i [4], 2'h0, \genrow[0].gencol[1].x_sw_full_o [3], \genrow[0].gencol[2].x_sw_full_i [0] }),
    .nxt_fifo_overflow_i({ \genrow[0].gencol[2].x_sw_ovrflw_i [4], 2'h0, \genrow[0].gencol[1].x_sw_ovrflw_o [3], \genrow[0].gencol[2].x_sw_ovrflw_i [0] }),
    .pckt_sw_i({ \genrow[0].gencol[2].x_sw_pckt_i [59:48], 24'h000000, \genrow[0].gencol[1].x_sw_pckt_o [47:36], \genrow[0].gencol[2].x_sw_pckt_i [11:0] }),
    .pckt_sw_o({ \genrow[0].gencol[2].x_sw_pckt_o [59:24], \genrow[0].gencol[1].x_sw_pckt_i [47:36], rsc_pckt_i[35:24] }),
    .rst_ni(rst_ni),
    .wr_en_sw_i({ \genrow[0].gencol[2].x_sw_wren_i [4], 2'h0, \genrow[0].gencol[1].x_sw_wren_o [3], \genrow[0].gencol[2].x_sw_wren_i [0] }),
    .wr_en_sw_o({ \genrow[0].gencol[2].x_sw_wren_o [4:2], \genrow[0].gencol[1].x_sw_wren_i [3], rsc_wren_i[2] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/noc/mesh_xy_noc.v:145.11-157.14" *)
  xy_switch #(
    .IN_FIFO_DEPTH_W(32'sd3),
    .PCKT_DATA_W(32'sd8),
    .PCKT_W(32'sd12),
    .PCKT_XADDR_W(32'sd2),
    .PCKT_YADDR_W(32'sd2),
    .PORT_N(3'h5),
    .SW_CONFIG(32'sd0),
    .X_CORD(32'sd1),
    .Y_CORD(32'sd0)
  ) \genrow[1].gencol[0].x_sw  (
    .clk_i(clk_i),
    .in_fifo_full_o({ \genrow[1].gencol[0].x_sw_full_o [4:3], \genrow[0].gencol[0].x_sw_full_i [4], \genrow[1].gencol[0].x_sw_full_o [1], rsc_full_i[3] }),
    .in_fifo_overflow_o({ \genrow[1].gencol[0].x_sw_ovrflw_o [4:3], \genrow[0].gencol[0].x_sw_ovrflw_i [4], \genrow[1].gencol[0].x_sw_ovrflw_o [1], rsc_ovrflw_i[3] }),
    .nxt_fifo_full_i({ \genrow[1].gencol[0].x_sw_full_i [4:3], \genrow[0].gencol[0].x_sw_full_o [4], 1'h0, \genrow[1].gencol[0].x_sw_full_i [0] }),
    .nxt_fifo_overflow_i({ \genrow[1].gencol[0].x_sw_ovrflw_i [4:3], \genrow[0].gencol[0].x_sw_ovrflw_o [4], 1'h0, \genrow[1].gencol[0].x_sw_ovrflw_i [0] }),
    .pckt_sw_i({ \genrow[1].gencol[0].x_sw_pckt_i [59:36], \genrow[0].gencol[0].x_sw_pckt_o [59:48], 12'h000, \genrow[1].gencol[0].x_sw_pckt_i [11:0] }),
    .pckt_sw_o({ \genrow[1].gencol[0].x_sw_pckt_o [59:36], \genrow[0].gencol[0].x_sw_pckt_i [59:48], \genrow[1].gencol[0].x_sw_pckt_o [23:12], rsc_pckt_i[47:36] }),
    .rst_ni(rst_ni),
    .wr_en_sw_i({ \genrow[1].gencol[0].x_sw_wren_i [4:3], \genrow[0].gencol[0].x_sw_wren_o [4], 1'h0, \genrow[1].gencol[0].x_sw_wren_i [0] }),
    .wr_en_sw_o({ \genrow[1].gencol[0].x_sw_wren_o [4:3], \genrow[0].gencol[0].x_sw_wren_i [4], \genrow[1].gencol[0].x_sw_wren_o [1], rsc_wren_i[3] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/noc/mesh_xy_noc.v:145.11-157.14" *)
  xy_switch #(
    .IN_FIFO_DEPTH_W(32'sd3),
    .PCKT_DATA_W(32'sd8),
    .PCKT_W(32'sd12),
    .PCKT_XADDR_W(32'sd2),
    .PCKT_YADDR_W(32'sd2),
    .PORT_N(3'h5),
    .SW_CONFIG(32'sd0),
    .X_CORD(32'sd1),
    .Y_CORD(32'sd1)
  ) \genrow[1].gencol[1].x_sw  (
    .clk_i(clk_i),
    .in_fifo_full_o({ \genrow[1].gencol[1].x_sw_full_o [4:3], \genrow[0].gencol[1].x_sw_full_i [4], \genrow[1].gencol[0].x_sw_full_i [3], rsc_full_i[4] }),
    .in_fifo_overflow_o({ \genrow[1].gencol[1].x_sw_ovrflw_o [4:3], \genrow[0].gencol[1].x_sw_ovrflw_i [4], \genrow[1].gencol[0].x_sw_ovrflw_i [3], rsc_ovrflw_i[4] }),
    .nxt_fifo_full_i({ \genrow[1].gencol[1].x_sw_full_i [4:3], \genrow[0].gencol[1].x_sw_full_o [4], \genrow[1].gencol[0].x_sw_full_o [3], \genrow[1].gencol[1].x_sw_full_i [0] }),
    .nxt_fifo_overflow_i({ \genrow[1].gencol[1].x_sw_ovrflw_i [4:3], \genrow[0].gencol[1].x_sw_ovrflw_o [4], \genrow[1].gencol[0].x_sw_ovrflw_o [3], \genrow[1].gencol[1].x_sw_ovrflw_i [0] }),
    .pckt_sw_i({ \genrow[1].gencol[1].x_sw_pckt_i [59:36], \genrow[0].gencol[1].x_sw_pckt_o [59:48], \genrow[1].gencol[0].x_sw_pckt_o [47:36], \genrow[1].gencol[1].x_sw_pckt_i [11:0] }),
    .pckt_sw_o({ \genrow[1].gencol[1].x_sw_pckt_o [59:36], \genrow[0].gencol[1].x_sw_pckt_i [59:48], \genrow[1].gencol[0].x_sw_pckt_i [47:36], rsc_pckt_i[59:48] }),
    .rst_ni(rst_ni),
    .wr_en_sw_i({ \genrow[1].gencol[1].x_sw_wren_i [4:3], \genrow[0].gencol[1].x_sw_wren_o [4], \genrow[1].gencol[0].x_sw_wren_o [3], \genrow[1].gencol[1].x_sw_wren_i [0] }),
    .wr_en_sw_o({ \genrow[1].gencol[1].x_sw_wren_o [4:3], \genrow[0].gencol[1].x_sw_wren_i [4], \genrow[1].gencol[0].x_sw_wren_i [3], rsc_wren_i[4] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/noc/mesh_xy_noc.v:145.11-157.14" *)
  xy_switch #(
    .IN_FIFO_DEPTH_W(32'sd3),
    .PCKT_DATA_W(32'sd8),
    .PCKT_W(32'sd12),
    .PCKT_XADDR_W(32'sd2),
    .PCKT_YADDR_W(32'sd2),
    .PORT_N(3'h5),
    .SW_CONFIG(32'sd0),
    .X_CORD(32'sd1),
    .Y_CORD(32'sd2)
  ) \genrow[1].gencol[2].x_sw  (
    .clk_i(clk_i),
    .in_fifo_full_o({ \genrow[1].gencol[2].x_sw_full_o [4:3], \genrow[0].gencol[2].x_sw_full_i [4], \genrow[1].gencol[1].x_sw_full_i [3], rsc_full_i[5] }),
    .in_fifo_overflow_o({ \genrow[1].gencol[2].x_sw_ovrflw_o [4:3], \genrow[0].gencol[2].x_sw_ovrflw_i [4], \genrow[1].gencol[1].x_sw_ovrflw_i [3], rsc_ovrflw_i[5] }),
    .nxt_fifo_full_i({ \genrow[1].gencol[2].x_sw_full_i [4], 1'h0, \genrow[0].gencol[2].x_sw_full_o [4], \genrow[1].gencol[1].x_sw_full_o [3], \genrow[1].gencol[2].x_sw_full_i [0] }),
    .nxt_fifo_overflow_i({ \genrow[1].gencol[2].x_sw_ovrflw_i [4], 1'h0, \genrow[0].gencol[2].x_sw_ovrflw_o [4], \genrow[1].gencol[1].x_sw_ovrflw_o [3], \genrow[1].gencol[2].x_sw_ovrflw_i [0] }),
    .pckt_sw_i({ \genrow[1].gencol[2].x_sw_pckt_i [59:48], 12'h000, \genrow[0].gencol[2].x_sw_pckt_o [59:48], \genrow[1].gencol[1].x_sw_pckt_o [47:36], \genrow[1].gencol[2].x_sw_pckt_i [11:0] }),
    .pckt_sw_o({ \genrow[1].gencol[2].x_sw_pckt_o [59:36], \genrow[0].gencol[2].x_sw_pckt_i [59:48], \genrow[1].gencol[1].x_sw_pckt_i [47:36], rsc_pckt_i[71:60] }),
    .rst_ni(rst_ni),
    .wr_en_sw_i({ \genrow[1].gencol[2].x_sw_wren_i [4], 1'h0, \genrow[0].gencol[2].x_sw_wren_o [4], \genrow[1].gencol[1].x_sw_wren_o [3], \genrow[1].gencol[2].x_sw_wren_i [0] }),
    .wr_en_sw_o({ \genrow[1].gencol[2].x_sw_wren_o [4:3], \genrow[0].gencol[2].x_sw_wren_i [4], \genrow[1].gencol[1].x_sw_wren_i [3], rsc_wren_i[5] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/noc/mesh_xy_noc.v:145.11-157.14" *)
  xy_switch #(
    .IN_FIFO_DEPTH_W(32'sd3),
    .PCKT_DATA_W(32'sd8),
    .PCKT_W(32'sd12),
    .PCKT_XADDR_W(32'sd2),
    .PCKT_YADDR_W(32'sd2),
    .PORT_N(3'h5),
    .SW_CONFIG(32'sd0),
    .X_CORD(32'sd2),
    .Y_CORD(32'sd0)
  ) \genrow[2].gencol[0].x_sw  (
    .clk_i(clk_i),
    .in_fifo_full_o({ \genrow[2].gencol[0].x_sw_full_o [4:3], \genrow[1].gencol[0].x_sw_full_i [4], \genrow[2].gencol[0].x_sw_full_o [1], rsc_full_i[6] }),
    .in_fifo_overflow_o({ \genrow[2].gencol[0].x_sw_ovrflw_o [4:3], \genrow[1].gencol[0].x_sw_ovrflw_i [4], \genrow[2].gencol[0].x_sw_ovrflw_o [1], rsc_ovrflw_i[6] }),
    .nxt_fifo_full_i({ 1'h0, \genrow[2].gencol[0].x_sw_full_i [3], \genrow[1].gencol[0].x_sw_full_o [4], 1'h0, \genrow[2].gencol[0].x_sw_full_i [0] }),
    .nxt_fifo_overflow_i({ 1'h0, \genrow[2].gencol[0].x_sw_ovrflw_i [3], \genrow[1].gencol[0].x_sw_ovrflw_o [4], 1'h0, \genrow[2].gencol[0].x_sw_ovrflw_i [0] }),
    .pckt_sw_i({ 12'h000, \genrow[2].gencol[0].x_sw_pckt_i [47:36], \genrow[1].gencol[0].x_sw_pckt_o [59:48], 12'h000, \genrow[2].gencol[0].x_sw_pckt_i [11:0] }),
    .pckt_sw_o({ \genrow[2].gencol[0].x_sw_pckt_o [59:36], \genrow[1].gencol[0].x_sw_pckt_i [59:48], \genrow[2].gencol[0].x_sw_pckt_o [23:12], rsc_pckt_i[83:72] }),
    .rst_ni(rst_ni),
    .wr_en_sw_i({ 1'h0, \genrow[2].gencol[0].x_sw_wren_i [3], \genrow[1].gencol[0].x_sw_wren_o [4], 1'h0, \genrow[2].gencol[0].x_sw_wren_i [0] }),
    .wr_en_sw_o({ \genrow[2].gencol[0].x_sw_wren_o [4:3], \genrow[1].gencol[0].x_sw_wren_i [4], \genrow[2].gencol[0].x_sw_wren_o [1], rsc_wren_i[6] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/noc/mesh_xy_noc.v:145.11-157.14" *)
  xy_switch #(
    .IN_FIFO_DEPTH_W(32'sd3),
    .PCKT_DATA_W(32'sd8),
    .PCKT_W(32'sd12),
    .PCKT_XADDR_W(32'sd2),
    .PCKT_YADDR_W(32'sd2),
    .PORT_N(3'h5),
    .SW_CONFIG(32'sd0),
    .X_CORD(32'sd2),
    .Y_CORD(32'sd1)
  ) \genrow[2].gencol[1].x_sw  (
    .clk_i(clk_i),
    .in_fifo_full_o({ \genrow[2].gencol[1].x_sw_full_o [4:3], \genrow[1].gencol[1].x_sw_full_i [4], \genrow[2].gencol[0].x_sw_full_i [3], rsc_full_i[7] }),
    .in_fifo_overflow_o({ \genrow[2].gencol[1].x_sw_ovrflw_o [4:3], \genrow[1].gencol[1].x_sw_ovrflw_i [4], \genrow[2].gencol[0].x_sw_ovrflw_i [3], rsc_ovrflw_i[7] }),
    .nxt_fifo_full_i({ 1'h0, \genrow[2].gencol[1].x_sw_full_i [3], \genrow[1].gencol[1].x_sw_full_o [4], \genrow[2].gencol[0].x_sw_full_o [3], \genrow[2].gencol[1].x_sw_full_i [0] }),
    .nxt_fifo_overflow_i({ 1'h0, \genrow[2].gencol[1].x_sw_ovrflw_i [3], \genrow[1].gencol[1].x_sw_ovrflw_o [4], \genrow[2].gencol[0].x_sw_ovrflw_o [3], \genrow[2].gencol[1].x_sw_ovrflw_i [0] }),
    .pckt_sw_i({ 12'h000, \genrow[2].gencol[1].x_sw_pckt_i [47:36], \genrow[1].gencol[1].x_sw_pckt_o [59:48], \genrow[2].gencol[0].x_sw_pckt_o [47:36], \genrow[2].gencol[1].x_sw_pckt_i [11:0] }),
    .pckt_sw_o({ \genrow[2].gencol[1].x_sw_pckt_o [59:36], \genrow[1].gencol[1].x_sw_pckt_i [59:48], \genrow[2].gencol[0].x_sw_pckt_i [47:36], rsc_pckt_i[95:84] }),
    .rst_ni(rst_ni),
    .wr_en_sw_i({ 1'h0, \genrow[2].gencol[1].x_sw_wren_i [3], \genrow[1].gencol[1].x_sw_wren_o [4], \genrow[2].gencol[0].x_sw_wren_o [3], \genrow[2].gencol[1].x_sw_wren_i [0] }),
    .wr_en_sw_o({ \genrow[2].gencol[1].x_sw_wren_o [4:3], \genrow[1].gencol[1].x_sw_wren_i [4], \genrow[2].gencol[0].x_sw_wren_i [3], rsc_wren_i[7] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../srcs/noc/mesh_xy_noc.v:145.11-157.14" *)
  xy_switch #(
    .IN_FIFO_DEPTH_W(32'sd3),
    .PCKT_DATA_W(32'sd8),
    .PCKT_W(32'sd12),
    .PCKT_XADDR_W(32'sd2),
    .PCKT_YADDR_W(32'sd2),
    .PORT_N(3'h5),
    .SW_CONFIG(32'sd0),
    .X_CORD(32'sd2),
    .Y_CORD(32'sd2)
  ) \genrow[2].gencol[2].x_sw  (
    .clk_i(clk_i),
    .in_fifo_full_o({ \genrow[2].gencol[2].x_sw_full_o [4:3], \genrow[1].gencol[2].x_sw_full_i [4], \genrow[2].gencol[1].x_sw_full_i [3], rsc_full_i[8] }),
    .in_fifo_overflow_o({ \genrow[2].gencol[2].x_sw_ovrflw_o [4:3], \genrow[1].gencol[2].x_sw_ovrflw_i [4], \genrow[2].gencol[1].x_sw_ovrflw_i [3], rsc_ovrflw_i[8] }),
    .nxt_fifo_full_i({ 2'h0, \genrow[1].gencol[2].x_sw_full_o [4], \genrow[2].gencol[1].x_sw_full_o [3], \genrow[2].gencol[2].x_sw_full_i [0] }),
    .nxt_fifo_overflow_i({ 2'h0, \genrow[1].gencol[2].x_sw_ovrflw_o [4], \genrow[2].gencol[1].x_sw_ovrflw_o [3], \genrow[2].gencol[2].x_sw_ovrflw_i [0] }),
    .pckt_sw_i({ 24'h000000, \genrow[1].gencol[2].x_sw_pckt_o [59:48], \genrow[2].gencol[1].x_sw_pckt_o [47:36], \genrow[2].gencol[2].x_sw_pckt_i [11:0] }),
    .pckt_sw_o({ \genrow[2].gencol[2].x_sw_pckt_o [59:36], \genrow[1].gencol[2].x_sw_pckt_i [59:48], \genrow[2].gencol[1].x_sw_pckt_i [47:36], rsc_pckt_i[107:96] }),
    .rst_ni(rst_ni),
    .wr_en_sw_i({ 2'h0, \genrow[1].gencol[2].x_sw_wren_o [4], \genrow[2].gencol[1].x_sw_wren_o [3], \genrow[2].gencol[2].x_sw_wren_i [0] }),
    .wr_en_sw_o({ \genrow[2].gencol[2].x_sw_wren_o [4:3], \genrow[1].gencol[2].x_sw_wren_i [4], \genrow[2].gencol[1].x_sw_wren_i [3], rsc_wren_i[8] })
  );
  assign \genrow[0].gencol[0].x_sw_full_i [2:1] = 2'h0;
  assign \genrow[0].gencol[0].x_sw_full_o [0] = rsc_full_i[0];
  assign \genrow[0].gencol[0].x_sw_ovrflw_i [2:1] = 2'h0;
  assign \genrow[0].gencol[0].x_sw_ovrflw_o [0] = rsc_ovrflw_i[0];
  assign \genrow[0].gencol[0].x_sw_pckt_i [35:12] = 24'h000000;
  assign \genrow[0].gencol[0].x_sw_pckt_o [11:0] = rsc_pckt_i[11:0];
  assign \genrow[0].gencol[0].x_sw_wren_i [2:1] = 2'h0;
  assign \genrow[0].gencol[0].x_sw_wren_o [0] = rsc_wren_i[0];
  assign \genrow[0].gencol[1].x_sw_full_i [2:1] = { 1'h0, \genrow[0].gencol[0].x_sw_full_o [3] };
  assign \genrow[0].gencol[1].x_sw_full_o [1:0] = { \genrow[0].gencol[0].x_sw_full_i [3], rsc_full_i[1] };
  assign \genrow[0].gencol[1].x_sw_ovrflw_i [2:1] = { 1'h0, \genrow[0].gencol[0].x_sw_ovrflw_o [3] };
  assign \genrow[0].gencol[1].x_sw_ovrflw_o [1:0] = { \genrow[0].gencol[0].x_sw_ovrflw_i [3], rsc_ovrflw_i[1] };
  assign \genrow[0].gencol[1].x_sw_pckt_i [35:12] = { 12'h000, \genrow[0].gencol[0].x_sw_pckt_o [47:36] };
  assign \genrow[0].gencol[1].x_sw_pckt_o [23:0] = { \genrow[0].gencol[0].x_sw_pckt_i [47:36], rsc_pckt_i[23:12] };
  assign \genrow[0].gencol[1].x_sw_wren_i [2:1] = { 1'h0, \genrow[0].gencol[0].x_sw_wren_o [3] };
  assign \genrow[0].gencol[1].x_sw_wren_o [1:0] = { \genrow[0].gencol[0].x_sw_wren_i [3], rsc_wren_i[1] };
  assign \genrow[0].gencol[2].x_sw_full_i [3:1] = { 2'h0, \genrow[0].gencol[1].x_sw_full_o [3] };
  assign \genrow[0].gencol[2].x_sw_full_o [1:0] = { \genrow[0].gencol[1].x_sw_full_i [3], rsc_full_i[2] };
  assign \genrow[0].gencol[2].x_sw_ovrflw_i [3:1] = { 2'h0, \genrow[0].gencol[1].x_sw_ovrflw_o [3] };
  assign \genrow[0].gencol[2].x_sw_ovrflw_o [1:0] = { \genrow[0].gencol[1].x_sw_ovrflw_i [3], rsc_ovrflw_i[2] };
  assign \genrow[0].gencol[2].x_sw_pckt_i [47:12] = { 24'h000000, \genrow[0].gencol[1].x_sw_pckt_o [47:36] };
  assign \genrow[0].gencol[2].x_sw_pckt_o [23:0] = { \genrow[0].gencol[1].x_sw_pckt_i [47:36], rsc_pckt_i[35:24] };
  assign \genrow[0].gencol[2].x_sw_wren_i [3:1] = { 2'h0, \genrow[0].gencol[1].x_sw_wren_o [3] };
  assign \genrow[0].gencol[2].x_sw_wren_o [1:0] = { \genrow[0].gencol[1].x_sw_wren_i [3], rsc_wren_i[2] };
  assign \genrow[1].gencol[0].x_sw_full_i [2:1] = { \genrow[0].gencol[0].x_sw_full_o [4], 1'h0 };
  assign { \genrow[1].gencol[0].x_sw_full_o [2], \genrow[1].gencol[0].x_sw_full_o [0] } = { \genrow[0].gencol[0].x_sw_full_i [4], rsc_full_i[3] };
  assign \genrow[1].gencol[0].x_sw_ovrflw_i [2:1] = { \genrow[0].gencol[0].x_sw_ovrflw_o [4], 1'h0 };
  assign { \genrow[1].gencol[0].x_sw_ovrflw_o [2], \genrow[1].gencol[0].x_sw_ovrflw_o [0] } = { \genrow[0].gencol[0].x_sw_ovrflw_i [4], rsc_ovrflw_i[3] };
  assign \genrow[1].gencol[0].x_sw_pckt_i [35:12] = { \genrow[0].gencol[0].x_sw_pckt_o [59:48], 12'h000 };
  assign { \genrow[1].gencol[0].x_sw_pckt_o [35:24], \genrow[1].gencol[0].x_sw_pckt_o [11:0] } = { \genrow[0].gencol[0].x_sw_pckt_i [59:48], rsc_pckt_i[47:36] };
  assign \genrow[1].gencol[0].x_sw_wren_i [2:1] = { \genrow[0].gencol[0].x_sw_wren_o [4], 1'h0 };
  assign { \genrow[1].gencol[0].x_sw_wren_o [2], \genrow[1].gencol[0].x_sw_wren_o [0] } = { \genrow[0].gencol[0].x_sw_wren_i [4], rsc_wren_i[3] };
  assign \genrow[1].gencol[1].x_sw_full_i [2:1] = { \genrow[0].gencol[1].x_sw_full_o [4], \genrow[1].gencol[0].x_sw_full_o [3] };
  assign \genrow[1].gencol[1].x_sw_full_o [2:0] = { \genrow[0].gencol[1].x_sw_full_i [4], \genrow[1].gencol[0].x_sw_full_i [3], rsc_full_i[4] };
  assign \genrow[1].gencol[1].x_sw_ovrflw_i [2:1] = { \genrow[0].gencol[1].x_sw_ovrflw_o [4], \genrow[1].gencol[0].x_sw_ovrflw_o [3] };
  assign \genrow[1].gencol[1].x_sw_ovrflw_o [2:0] = { \genrow[0].gencol[1].x_sw_ovrflw_i [4], \genrow[1].gencol[0].x_sw_ovrflw_i [3], rsc_ovrflw_i[4] };
  assign \genrow[1].gencol[1].x_sw_pckt_i [35:12] = { \genrow[0].gencol[1].x_sw_pckt_o [59:48], \genrow[1].gencol[0].x_sw_pckt_o [47:36] };
  assign \genrow[1].gencol[1].x_sw_pckt_o [35:0] = { \genrow[0].gencol[1].x_sw_pckt_i [59:48], \genrow[1].gencol[0].x_sw_pckt_i [47:36], rsc_pckt_i[59:48] };
  assign \genrow[1].gencol[1].x_sw_wren_i [2:1] = { \genrow[0].gencol[1].x_sw_wren_o [4], \genrow[1].gencol[0].x_sw_wren_o [3] };
  assign \genrow[1].gencol[1].x_sw_wren_o [2:0] = { \genrow[0].gencol[1].x_sw_wren_i [4], \genrow[1].gencol[0].x_sw_wren_i [3], rsc_wren_i[4] };
  assign \genrow[1].gencol[2].x_sw_full_i [3:1] = { 1'h0, \genrow[0].gencol[2].x_sw_full_o [4], \genrow[1].gencol[1].x_sw_full_o [3] };
  assign \genrow[1].gencol[2].x_sw_full_o [2:0] = { \genrow[0].gencol[2].x_sw_full_i [4], \genrow[1].gencol[1].x_sw_full_i [3], rsc_full_i[5] };
  assign \genrow[1].gencol[2].x_sw_ovrflw_i [3:1] = { 1'h0, \genrow[0].gencol[2].x_sw_ovrflw_o [4], \genrow[1].gencol[1].x_sw_ovrflw_o [3] };
  assign \genrow[1].gencol[2].x_sw_ovrflw_o [2:0] = { \genrow[0].gencol[2].x_sw_ovrflw_i [4], \genrow[1].gencol[1].x_sw_ovrflw_i [3], rsc_ovrflw_i[5] };
  assign \genrow[1].gencol[2].x_sw_pckt_i [47:12] = { 12'h000, \genrow[0].gencol[2].x_sw_pckt_o [59:48], \genrow[1].gencol[1].x_sw_pckt_o [47:36] };
  assign \genrow[1].gencol[2].x_sw_pckt_o [35:0] = { \genrow[0].gencol[2].x_sw_pckt_i [59:48], \genrow[1].gencol[1].x_sw_pckt_i [47:36], rsc_pckt_i[71:60] };
  assign \genrow[1].gencol[2].x_sw_wren_i [3:1] = { 1'h0, \genrow[0].gencol[2].x_sw_wren_o [4], \genrow[1].gencol[1].x_sw_wren_o [3] };
  assign \genrow[1].gencol[2].x_sw_wren_o [2:0] = { \genrow[0].gencol[2].x_sw_wren_i [4], \genrow[1].gencol[1].x_sw_wren_i [3], rsc_wren_i[5] };
  assign { \genrow[2].gencol[0].x_sw_full_i [4], \genrow[2].gencol[0].x_sw_full_i [2:1] } = { 1'h0, \genrow[1].gencol[0].x_sw_full_o [4], 1'h0 };
  assign { \genrow[2].gencol[0].x_sw_full_o [2], \genrow[2].gencol[0].x_sw_full_o [0] } = { \genrow[1].gencol[0].x_sw_full_i [4], rsc_full_i[6] };
  assign { \genrow[2].gencol[0].x_sw_ovrflw_i [4], \genrow[2].gencol[0].x_sw_ovrflw_i [2:1] } = { 1'h0, \genrow[1].gencol[0].x_sw_ovrflw_o [4], 1'h0 };
  assign { \genrow[2].gencol[0].x_sw_ovrflw_o [2], \genrow[2].gencol[0].x_sw_ovrflw_o [0] } = { \genrow[1].gencol[0].x_sw_ovrflw_i [4], rsc_ovrflw_i[6] };
  assign { \genrow[2].gencol[0].x_sw_pckt_i [59:48], \genrow[2].gencol[0].x_sw_pckt_i [35:12] } = { 12'h000, \genrow[1].gencol[0].x_sw_pckt_o [59:48], 12'h000 };
  assign { \genrow[2].gencol[0].x_sw_pckt_o [35:24], \genrow[2].gencol[0].x_sw_pckt_o [11:0] } = { \genrow[1].gencol[0].x_sw_pckt_i [59:48], rsc_pckt_i[83:72] };
  assign { \genrow[2].gencol[0].x_sw_wren_i [4], \genrow[2].gencol[0].x_sw_wren_i [2:1] } = { 1'h0, \genrow[1].gencol[0].x_sw_wren_o [4], 1'h0 };
  assign { \genrow[2].gencol[0].x_sw_wren_o [2], \genrow[2].gencol[0].x_sw_wren_o [0] } = { \genrow[1].gencol[0].x_sw_wren_i [4], rsc_wren_i[6] };
  assign { \genrow[2].gencol[1].x_sw_full_i [4], \genrow[2].gencol[1].x_sw_full_i [2:1] } = { 1'h0, \genrow[1].gencol[1].x_sw_full_o [4], \genrow[2].gencol[0].x_sw_full_o [3] };
  assign \genrow[2].gencol[1].x_sw_full_o [2:0] = { \genrow[1].gencol[1].x_sw_full_i [4], \genrow[2].gencol[0].x_sw_full_i [3], rsc_full_i[7] };
  assign { \genrow[2].gencol[1].x_sw_ovrflw_i [4], \genrow[2].gencol[1].x_sw_ovrflw_i [2:1] } = { 1'h0, \genrow[1].gencol[1].x_sw_ovrflw_o [4], \genrow[2].gencol[0].x_sw_ovrflw_o [3] };
  assign \genrow[2].gencol[1].x_sw_ovrflw_o [2:0] = { \genrow[1].gencol[1].x_sw_ovrflw_i [4], \genrow[2].gencol[0].x_sw_ovrflw_i [3], rsc_ovrflw_i[7] };
  assign { \genrow[2].gencol[1].x_sw_pckt_i [59:48], \genrow[2].gencol[1].x_sw_pckt_i [35:12] } = { 12'h000, \genrow[1].gencol[1].x_sw_pckt_o [59:48], \genrow[2].gencol[0].x_sw_pckt_o [47:36] };
  assign \genrow[2].gencol[1].x_sw_pckt_o [35:0] = { \genrow[1].gencol[1].x_sw_pckt_i [59:48], \genrow[2].gencol[0].x_sw_pckt_i [47:36], rsc_pckt_i[95:84] };
  assign { \genrow[2].gencol[1].x_sw_wren_i [4], \genrow[2].gencol[1].x_sw_wren_i [2:1] } = { 1'h0, \genrow[1].gencol[1].x_sw_wren_o [4], \genrow[2].gencol[0].x_sw_wren_o [3] };
  assign \genrow[2].gencol[1].x_sw_wren_o [2:0] = { \genrow[1].gencol[1].x_sw_wren_i [4], \genrow[2].gencol[0].x_sw_wren_i [3], rsc_wren_i[7] };
  assign \genrow[2].gencol[2].x_sw_full_i [4:1] = { 2'h0, \genrow[1].gencol[2].x_sw_full_o [4], \genrow[2].gencol[1].x_sw_full_o [3] };
  assign \genrow[2].gencol[2].x_sw_full_o [2:0] = { \genrow[1].gencol[2].x_sw_full_i [4], \genrow[2].gencol[1].x_sw_full_i [3], rsc_full_i[8] };
  assign \genrow[2].gencol[2].x_sw_ovrflw_i [4:1] = { 2'h0, \genrow[1].gencol[2].x_sw_ovrflw_o [4], \genrow[2].gencol[1].x_sw_ovrflw_o [3] };
  assign \genrow[2].gencol[2].x_sw_ovrflw_o [2:0] = { \genrow[1].gencol[2].x_sw_ovrflw_i [4], \genrow[2].gencol[1].x_sw_ovrflw_i [3], rsc_ovrflw_i[8] };
  assign \genrow[2].gencol[2].x_sw_pckt_i [59:12] = { 24'h000000, \genrow[1].gencol[2].x_sw_pckt_o [59:48], \genrow[2].gencol[1].x_sw_pckt_o [47:36] };
  assign \genrow[2].gencol[2].x_sw_pckt_o [35:0] = { \genrow[1].gencol[2].x_sw_pckt_i [59:48], \genrow[2].gencol[1].x_sw_pckt_i [47:36], rsc_pckt_i[107:96] };
  assign \genrow[2].gencol[2].x_sw_wren_i [4:1] = { 2'h0, \genrow[1].gencol[2].x_sw_wren_o [4], \genrow[2].gencol[1].x_sw_wren_o [3] };
  assign \genrow[2].gencol[2].x_sw_wren_o [2:0] = { \genrow[1].gencol[2].x_sw_wren_i [4], \genrow[2].gencol[1].x_sw_wren_i [3], rsc_wren_i[8] };
  assign rsc_full_o = { \genrow[2].gencol[2].x_sw_full_i [0], \genrow[2].gencol[1].x_sw_full_i [0], \genrow[2].gencol[0].x_sw_full_i [0], \genrow[1].gencol[2].x_sw_full_i [0], \genrow[1].gencol[1].x_sw_full_i [0], \genrow[1].gencol[0].x_sw_full_i [0], \genrow[0].gencol[2].x_sw_full_i [0], \genrow[0].gencol[1].x_sw_full_i [0], \genrow[0].gencol[0].x_sw_full_i [0] };
  assign rsc_ovrflw_o = { \genrow[2].gencol[2].x_sw_ovrflw_i [0], \genrow[2].gencol[1].x_sw_ovrflw_i [0], \genrow[2].gencol[0].x_sw_ovrflw_i [0], \genrow[1].gencol[2].x_sw_ovrflw_i [0], \genrow[1].gencol[1].x_sw_ovrflw_i [0], \genrow[1].gencol[0].x_sw_ovrflw_i [0], \genrow[0].gencol[2].x_sw_ovrflw_i [0], \genrow[0].gencol[1].x_sw_ovrflw_i [0], \genrow[0].gencol[0].x_sw_ovrflw_i [0] };
  assign rsc_pckt_o = { \genrow[2].gencol[2].x_sw_pckt_i [11:0], \genrow[2].gencol[1].x_sw_pckt_i [11:0], \genrow[2].gencol[0].x_sw_pckt_i [11:0], \genrow[1].gencol[2].x_sw_pckt_i [11:0], \genrow[1].gencol[1].x_sw_pckt_i [11:0], \genrow[1].gencol[0].x_sw_pckt_i [11:0], \genrow[0].gencol[2].x_sw_pckt_i [11:0], \genrow[0].gencol[1].x_sw_pckt_i [11:0], \genrow[0].gencol[0].x_sw_pckt_i [11:0] };
  assign rsc_wren_o = { \genrow[2].gencol[2].x_sw_wren_i [0], \genrow[2].gencol[1].x_sw_wren_i [0], \genrow[2].gencol[0].x_sw_wren_i [0], \genrow[1].gencol[2].x_sw_wren_i [0], \genrow[1].gencol[1].x_sw_wren_i [0], \genrow[1].gencol[0].x_sw_wren_i [0], \genrow[0].gencol[2].x_sw_wren_i [0], \genrow[0].gencol[1].x_sw_wren_i [0], \genrow[0].gencol[0].x_sw_wren_i [0] };
  assign \sw_full_w[0]  = \genrow[0].gencol[0].x_sw_full_o [1];
  assign \sw_full_w[10]  = \genrow[0].gencol[2].x_sw_full_o [3];
  assign \sw_full_w[11]  = \genrow[0].gencol[2].x_sw_full_o [4];
  assign \sw_full_w[12]  = \genrow[1].gencol[0].x_sw_full_o [1];
  assign \sw_full_w[13]  = \genrow[0].gencol[0].x_sw_full_i [4];
  assign \sw_full_w[14]  = \genrow[1].gencol[0].x_sw_full_o [3];
  assign \sw_full_w[15]  = \genrow[1].gencol[0].x_sw_full_o [4];
  assign \sw_full_w[16]  = \genrow[1].gencol[0].x_sw_full_i [3];
  assign \sw_full_w[17]  = \genrow[0].gencol[1].x_sw_full_i [4];
  assign \sw_full_w[18]  = \genrow[1].gencol[1].x_sw_full_o [3];
  assign \sw_full_w[19]  = \genrow[1].gencol[1].x_sw_full_o [4];
  assign \sw_full_w[1]  = \genrow[0].gencol[0].x_sw_full_o [2];
  assign \sw_full_w[20]  = \genrow[1].gencol[1].x_sw_full_i [3];
  assign \sw_full_w[21]  = \genrow[0].gencol[2].x_sw_full_i [4];
  assign \sw_full_w[22]  = \genrow[1].gencol[2].x_sw_full_o [3];
  assign \sw_full_w[23]  = \genrow[1].gencol[2].x_sw_full_o [4];
  assign \sw_full_w[24]  = \genrow[2].gencol[0].x_sw_full_o [1];
  assign \sw_full_w[25]  = \genrow[1].gencol[0].x_sw_full_i [4];
  assign \sw_full_w[26]  = \genrow[2].gencol[0].x_sw_full_o [3];
  assign \sw_full_w[27]  = \genrow[2].gencol[0].x_sw_full_o [4];
  assign \sw_full_w[28]  = \genrow[2].gencol[0].x_sw_full_i [3];
  assign \sw_full_w[29]  = \genrow[1].gencol[1].x_sw_full_i [4];
  assign \sw_full_w[2]  = \genrow[0].gencol[0].x_sw_full_o [3];
  assign \sw_full_w[30]  = \genrow[2].gencol[1].x_sw_full_o [3];
  assign \sw_full_w[31]  = \genrow[2].gencol[1].x_sw_full_o [4];
  assign \sw_full_w[32]  = \genrow[2].gencol[1].x_sw_full_i [3];
  assign \sw_full_w[33]  = \genrow[1].gencol[2].x_sw_full_i [4];
  assign \sw_full_w[34]  = \genrow[2].gencol[2].x_sw_full_o [3];
  assign \sw_full_w[35]  = \genrow[2].gencol[2].x_sw_full_o [4];
  assign \sw_full_w[3]  = \genrow[0].gencol[0].x_sw_full_o [4];
  assign \sw_full_w[4]  = \genrow[0].gencol[0].x_sw_full_i [3];
  assign \sw_full_w[5]  = \genrow[0].gencol[1].x_sw_full_o [2];
  assign \sw_full_w[6]  = \genrow[0].gencol[1].x_sw_full_o [3];
  assign \sw_full_w[7]  = \genrow[0].gencol[1].x_sw_full_o [4];
  assign \sw_full_w[8]  = \genrow[0].gencol[1].x_sw_full_i [3];
  assign \sw_full_w[9]  = \genrow[0].gencol[2].x_sw_full_o [2];
  assign \sw_ovrflw_w[0]  = \genrow[0].gencol[0].x_sw_ovrflw_o [1];
  assign \sw_ovrflw_w[10]  = \genrow[0].gencol[2].x_sw_ovrflw_o [3];
  assign \sw_ovrflw_w[11]  = \genrow[0].gencol[2].x_sw_ovrflw_o [4];
  assign \sw_ovrflw_w[12]  = \genrow[1].gencol[0].x_sw_ovrflw_o [1];
  assign \sw_ovrflw_w[13]  = \genrow[0].gencol[0].x_sw_ovrflw_i [4];
  assign \sw_ovrflw_w[14]  = \genrow[1].gencol[0].x_sw_ovrflw_o [3];
  assign \sw_ovrflw_w[15]  = \genrow[1].gencol[0].x_sw_ovrflw_o [4];
  assign \sw_ovrflw_w[16]  = \genrow[1].gencol[0].x_sw_ovrflw_i [3];
  assign \sw_ovrflw_w[17]  = \genrow[0].gencol[1].x_sw_ovrflw_i [4];
  assign \sw_ovrflw_w[18]  = \genrow[1].gencol[1].x_sw_ovrflw_o [3];
  assign \sw_ovrflw_w[19]  = \genrow[1].gencol[1].x_sw_ovrflw_o [4];
  assign \sw_ovrflw_w[1]  = \genrow[0].gencol[0].x_sw_ovrflw_o [2];
  assign \sw_ovrflw_w[20]  = \genrow[1].gencol[1].x_sw_ovrflw_i [3];
  assign \sw_ovrflw_w[21]  = \genrow[0].gencol[2].x_sw_ovrflw_i [4];
  assign \sw_ovrflw_w[22]  = \genrow[1].gencol[2].x_sw_ovrflw_o [3];
  assign \sw_ovrflw_w[23]  = \genrow[1].gencol[2].x_sw_ovrflw_o [4];
  assign \sw_ovrflw_w[24]  = \genrow[2].gencol[0].x_sw_ovrflw_o [1];
  assign \sw_ovrflw_w[25]  = \genrow[1].gencol[0].x_sw_ovrflw_i [4];
  assign \sw_ovrflw_w[26]  = \genrow[2].gencol[0].x_sw_ovrflw_o [3];
  assign \sw_ovrflw_w[27]  = \genrow[2].gencol[0].x_sw_ovrflw_o [4];
  assign \sw_ovrflw_w[28]  = \genrow[2].gencol[0].x_sw_ovrflw_i [3];
  assign \sw_ovrflw_w[29]  = \genrow[1].gencol[1].x_sw_ovrflw_i [4];
  assign \sw_ovrflw_w[2]  = \genrow[0].gencol[0].x_sw_ovrflw_o [3];
  assign \sw_ovrflw_w[30]  = \genrow[2].gencol[1].x_sw_ovrflw_o [3];
  assign \sw_ovrflw_w[31]  = \genrow[2].gencol[1].x_sw_ovrflw_o [4];
  assign \sw_ovrflw_w[32]  = \genrow[2].gencol[1].x_sw_ovrflw_i [3];
  assign \sw_ovrflw_w[33]  = \genrow[1].gencol[2].x_sw_ovrflw_i [4];
  assign \sw_ovrflw_w[34]  = \genrow[2].gencol[2].x_sw_ovrflw_o [3];
  assign \sw_ovrflw_w[35]  = \genrow[2].gencol[2].x_sw_ovrflw_o [4];
  assign \sw_ovrflw_w[3]  = \genrow[0].gencol[0].x_sw_ovrflw_o [4];
  assign \sw_ovrflw_w[4]  = \genrow[0].gencol[0].x_sw_ovrflw_i [3];
  assign \sw_ovrflw_w[5]  = \genrow[0].gencol[1].x_sw_ovrflw_o [2];
  assign \sw_ovrflw_w[6]  = \genrow[0].gencol[1].x_sw_ovrflw_o [3];
  assign \sw_ovrflw_w[7]  = \genrow[0].gencol[1].x_sw_ovrflw_o [4];
  assign \sw_ovrflw_w[8]  = \genrow[0].gencol[1].x_sw_ovrflw_i [3];
  assign \sw_ovrflw_w[9]  = \genrow[0].gencol[2].x_sw_ovrflw_o [2];
  assign \sw_pckt_w[0]  = \genrow[0].gencol[0].x_sw_pckt_o [23:12];
  assign \sw_pckt_w[10]  = \genrow[0].gencol[2].x_sw_pckt_o [47:36];
  assign \sw_pckt_w[11]  = \genrow[0].gencol[2].x_sw_pckt_o [59:48];
  assign \sw_pckt_w[12]  = \genrow[1].gencol[0].x_sw_pckt_o [23:12];
  assign \sw_pckt_w[13]  = \genrow[0].gencol[0].x_sw_pckt_i [59:48];
  assign \sw_pckt_w[14]  = \genrow[1].gencol[0].x_sw_pckt_o [47:36];
  assign \sw_pckt_w[15]  = \genrow[1].gencol[0].x_sw_pckt_o [59:48];
  assign \sw_pckt_w[16]  = \genrow[1].gencol[0].x_sw_pckt_i [47:36];
  assign \sw_pckt_w[17]  = \genrow[0].gencol[1].x_sw_pckt_i [59:48];
  assign \sw_pckt_w[18]  = \genrow[1].gencol[1].x_sw_pckt_o [47:36];
  assign \sw_pckt_w[19]  = \genrow[1].gencol[1].x_sw_pckt_o [59:48];
  assign \sw_pckt_w[1]  = \genrow[0].gencol[0].x_sw_pckt_o [35:24];
  assign \sw_pckt_w[20]  = \genrow[1].gencol[1].x_sw_pckt_i [47:36];
  assign \sw_pckt_w[21]  = \genrow[0].gencol[2].x_sw_pckt_i [59:48];
  assign \sw_pckt_w[22]  = \genrow[1].gencol[2].x_sw_pckt_o [47:36];
  assign \sw_pckt_w[23]  = \genrow[1].gencol[2].x_sw_pckt_o [59:48];
  assign \sw_pckt_w[24]  = \genrow[2].gencol[0].x_sw_pckt_o [23:12];
  assign \sw_pckt_w[25]  = \genrow[1].gencol[0].x_sw_pckt_i [59:48];
  assign \sw_pckt_w[26]  = \genrow[2].gencol[0].x_sw_pckt_o [47:36];
  assign \sw_pckt_w[27]  = \genrow[2].gencol[0].x_sw_pckt_o [59:48];
  assign \sw_pckt_w[28]  = \genrow[2].gencol[0].x_sw_pckt_i [47:36];
  assign \sw_pckt_w[29]  = \genrow[1].gencol[1].x_sw_pckt_i [59:48];
  assign \sw_pckt_w[2]  = \genrow[0].gencol[0].x_sw_pckt_o [47:36];
  assign \sw_pckt_w[30]  = \genrow[2].gencol[1].x_sw_pckt_o [47:36];
  assign \sw_pckt_w[31]  = \genrow[2].gencol[1].x_sw_pckt_o [59:48];
  assign \sw_pckt_w[32]  = \genrow[2].gencol[1].x_sw_pckt_i [47:36];
  assign \sw_pckt_w[33]  = \genrow[1].gencol[2].x_sw_pckt_i [59:48];
  assign \sw_pckt_w[34]  = \genrow[2].gencol[2].x_sw_pckt_o [47:36];
  assign \sw_pckt_w[35]  = \genrow[2].gencol[2].x_sw_pckt_o [59:48];
  assign \sw_pckt_w[3]  = \genrow[0].gencol[0].x_sw_pckt_o [59:48];
  assign \sw_pckt_w[4]  = \genrow[0].gencol[0].x_sw_pckt_i [47:36];
  assign \sw_pckt_w[5]  = \genrow[0].gencol[1].x_sw_pckt_o [35:24];
  assign \sw_pckt_w[6]  = \genrow[0].gencol[1].x_sw_pckt_o [47:36];
  assign \sw_pckt_w[7]  = \genrow[0].gencol[1].x_sw_pckt_o [59:48];
  assign \sw_pckt_w[8]  = \genrow[0].gencol[1].x_sw_pckt_i [47:36];
  assign \sw_pckt_w[9]  = \genrow[0].gencol[2].x_sw_pckt_o [35:24];
  assign \sw_wren_w[0]  = \genrow[0].gencol[0].x_sw_wren_o [1];
  assign \sw_wren_w[10]  = \genrow[0].gencol[2].x_sw_wren_o [3];
  assign \sw_wren_w[11]  = \genrow[0].gencol[2].x_sw_wren_o [4];
  assign \sw_wren_w[12]  = \genrow[1].gencol[0].x_sw_wren_o [1];
  assign \sw_wren_w[13]  = \genrow[0].gencol[0].x_sw_wren_i [4];
  assign \sw_wren_w[14]  = \genrow[1].gencol[0].x_sw_wren_o [3];
  assign \sw_wren_w[15]  = \genrow[1].gencol[0].x_sw_wren_o [4];
  assign \sw_wren_w[16]  = \genrow[1].gencol[0].x_sw_wren_i [3];
  assign \sw_wren_w[17]  = \genrow[0].gencol[1].x_sw_wren_i [4];
  assign \sw_wren_w[18]  = \genrow[1].gencol[1].x_sw_wren_o [3];
  assign \sw_wren_w[19]  = \genrow[1].gencol[1].x_sw_wren_o [4];
  assign \sw_wren_w[1]  = \genrow[0].gencol[0].x_sw_wren_o [2];
  assign \sw_wren_w[20]  = \genrow[1].gencol[1].x_sw_wren_i [3];
  assign \sw_wren_w[21]  = \genrow[0].gencol[2].x_sw_wren_i [4];
  assign \sw_wren_w[22]  = \genrow[1].gencol[2].x_sw_wren_o [3];
  assign \sw_wren_w[23]  = \genrow[1].gencol[2].x_sw_wren_o [4];
  assign \sw_wren_w[24]  = \genrow[2].gencol[0].x_sw_wren_o [1];
  assign \sw_wren_w[25]  = \genrow[1].gencol[0].x_sw_wren_i [4];
  assign \sw_wren_w[26]  = \genrow[2].gencol[0].x_sw_wren_o [3];
  assign \sw_wren_w[27]  = \genrow[2].gencol[0].x_sw_wren_o [4];
  assign \sw_wren_w[28]  = \genrow[2].gencol[0].x_sw_wren_i [3];
  assign \sw_wren_w[29]  = \genrow[1].gencol[1].x_sw_wren_i [4];
  assign \sw_wren_w[2]  = \genrow[0].gencol[0].x_sw_wren_o [3];
  assign \sw_wren_w[30]  = \genrow[2].gencol[1].x_sw_wren_o [3];
  assign \sw_wren_w[31]  = \genrow[2].gencol[1].x_sw_wren_o [4];
  assign \sw_wren_w[32]  = \genrow[2].gencol[1].x_sw_wren_i [3];
  assign \sw_wren_w[33]  = \genrow[1].gencol[2].x_sw_wren_i [4];
  assign \sw_wren_w[34]  = \genrow[2].gencol[2].x_sw_wren_o [3];
  assign \sw_wren_w[35]  = \genrow[2].gencol[2].x_sw_wren_o [4];
  assign \sw_wren_w[3]  = \genrow[0].gencol[0].x_sw_wren_o [4];
  assign \sw_wren_w[4]  = \genrow[0].gencol[0].x_sw_wren_i [3];
  assign \sw_wren_w[5]  = \genrow[0].gencol[1].x_sw_wren_o [2];
  assign \sw_wren_w[6]  = \genrow[0].gencol[1].x_sw_wren_o [3];
  assign \sw_wren_w[7]  = \genrow[0].gencol[1].x_sw_wren_o [4];
  assign \sw_wren_w[8]  = \genrow[0].gencol[1].x_sw_wren_i [3];
  assign \sw_wren_w[9]  = \genrow[0].gencol[2].x_sw_wren_o [2];
endmodule
