/* Generated by Yosys 0.9+4052 (git sha1 32a0ce9d, clang 12.0.0-1ubuntu1 -fPIC -Os) */

module BUF(A, Y);
  input A;
  output Y;
  assign Y = A;
endmodule

module DFF(C, D, Q);
  input C;
  input D;
  reg IQ;
  wire IQN;
  output Q;
  assign IQN = ~IQ;
  always @(posedge C)
    IQ <= D;
  assign Q = IQ;
endmodule

module DFFSR(C, D, Q, R, S);
  input C;
  input D;
  reg IQ;
  wire IQN;
  output Q;
  input R;
  input S;
  assign IQN = ~IQ;
  always @(posedge C, posedge S, posedge R)
    if (R) IQ <= 1'b0;
    else if (S) IQ <= 1'b1;
    else IQ <= D;
  assign Q = IQ;
endmodule

module NAND(A, B, Y);
  wire _0_;
  wire _1_;
  input A;
  input B;
  output Y;
  assign _0_ = ~_1_;
  assign _1_ = A & B;
  assign Y = _0_;
endmodule

module NOR(A, B, Y);
  wire _0_;
  wire _1_;
  input A;
  input B;
  output Y;
  assign _0_ = ~_1_;
  assign _1_ = A | B;
  assign Y = _0_;
endmodule

module NOT(A, Y);
  wire _0_;
  input A;
  output Y;
  assign _0_ = ~A;
  assign Y = _0_;
endmodule
