# This is a basic workflow to help you get started with Actions

name: Sim + Synth + Formal CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: PIP3 Requirements
        run: pip3 install -r requirements.txt

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  formal:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Arbiter
        run: |
          cd sim/formal
          sby -f arb.sby

      - name: FIFO
        run: |
          cd sim/formal
          sby -f fifo.sby

      - name: RouterXY
        run: |
          cd sim/formal
          sby -f rtr.sby

      - name: XY_SWITCH
        run: |
          cd sim/formal
          sby -f xy_switch.sby

  functional_presynth:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: [build, synth, formal]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: FIFO
        run: |
          cd sim/functional/circ_fifo
          python3 run_and_verify.py

      - name: XY_switch
        run: |
          cd sim/functional/xy_switch
          python3 run_and_verify.py -tf

      - name: Mesh XY Single
        run: |
          export CI=1
          cd sim/functional/mesh_xy_noc
          python3 run_and_verify.py -tf -ff_depth 6 -pckt_w 16 -row_n 3 -col_m 3

      # - name: Mesh XY Regression
      #   run: |
      #     cd sim/functional/mesh_xy_noc
      #     python3 run_and_verify.py -tf 1 -ff_depth 6 -pckt_w 14 -regression 1

      - name: VC
        run: |
          cd sim/functional/virtual_channel
          python3 run_and_verify.py

      - name: Wormhole XY Node
        run: |
          cd sim/functional/mesh_wormhole_switch
          python3 run_and_verify.py

      - name: Wormhole XY NoC
        run: |
          cd sim/functional/mesh_wh_xy_noc
          python3 run_and_verify.py -tf -ff_depth 3 -channel_w 9

  functional_postsynth:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: [build, synth, formal, functional_presynth]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: FIFO
        run: |
          cd sim/functional/circ_fifo
          python3 run_and_verify.py -ps -synth

      - name: Mesh XY 3x3
        run: |
          export CI=1
          cd sim/functional/mesh_xy_noc
          python3 run_and_verify.py -tf -ps -synth -ff_depth 6 -pckt_w 16 -row_n 3 -col_m 3

      - name: VC
        run: |
          cd sim/functional/virtual_channel
          python3 run_and_verify.py -ps -synth

      - name: Wormhole XY Node
        run: |
          cd sim/functional/mesh_wormhole_switch
          python3 run_and_verify.py -ps -synth

      - name: Wormhole XY NoC
        run: |
          cd sim/functional/mesh_wh_xy_noc
          python3 run_and_verify.py -ps -synth -tf -channel_w 9 -ff_depth 3

  synth:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: circ_fifo
        run: |
          cd synth
          ./yosys_wrapper.sh -sf fifo_synth.tcl --no-xdot

      - name: nxn_single_crossbar
        run: |
          cd synth
          ./yosys_wrapper.sh -sf nxn_single_crossbar.tcl --no-xdot

      - name: nxn parrallel crossbar
        run: |
          cd synth
          ./yosys_wrapper.sh -sf nxn_parrallel_crossbar.tcl --no-xdot

      - name: allocator
        run: |
          cd synth
          ./yosys_wrapper.sh -sf allocator.tcl --no-xdot

      - name: hop_cnt_arbiter
        run: |
          cd synth
          ./yosys_wrapper.sh -sf hop_cnt_arb.tcl --no-xdot

      - name: static_priority_arbiter
        run: |
          cd synth
          ./yosys_wrapper.sh -sf static_arb.tcl --no-xdot

      - name: router
        run: |
          cd synth
          ./yosys_wrapper.sh -sf router_synth.tcl --no-xdot

      - name: vc
        run: |
          cd synth
          ./yosys_wrapper.sh -sf virtual_channel.tcl --no-xdot

      - name: wormhole xy node
        run: |
          cd synth
          ./yosys_wrapper.sh -sf mesh_wormhole_node.tcl --no-xdot

      - name: sw_xy
        run: |
          cd synth
          ./yosys_wrapper.sh -sf sw_xy_synth.tcl --no-xdot

      - name: mesh_xy noc
        run: |
          cd synth
          ./yosys_wrapper.sh -sf mesh_xy_noc.tcl --no-xdot

      - name: wormhole xy noc
        run: |
          cd synth
          ./yosys_wrapper.sh -sf mesh_wh_xy_noc.tcl --no-xdot
