# This is a basic workflow to help you get started with Actions

name: NoC Measurements

# Controls when the action will run.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

  mesh_xy_noc_FF_D2:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: XY NoC
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_xy_noc
          python3 run_and_verify.py -tf -ff_depth 2 -row_n 3 -col_m 3

      - name: XY NoC 4x4
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_xy_noc
          python3 run_and_verify.py -tf -ff_depth 2 -row_n 4 -col_m 4

      - name: XY NoC 5x5
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_xy_noc
          python3 run_and_verify.py -tf -ff_depth 2 -row_n 5 -col_m 5

      - name: Upload JSONs
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: mesh_xy_noc_FF_D2
          path: sim/functional/mesh_xy_noc/*.json

  mesh_xy_noc_FF_D3:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: XY NoC 3x3
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_xy_noc
          python3 run_and_verify.py -tf -ff_depth 3 -row_n 3 -col_m 3

      - name: XY NoC 4x4
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_xy_noc
          python3 run_and_verify.py -tf -ff_depth 3 -row_n 4 -col_m 4

      - name: XY NoC 5x5
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_xy_noc
          python3 run_and_verify.py -tf -ff_depth 3 -row_n 5 -col_m 5

      - name: Upload JSONs
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: mesh_xy_noc_FF_D3
          path: sim/functional/mesh_xy_noc/*.json

  mesh_xy_noc_FF_D4:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: XY NoC 3x3
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_xy_noc
          python3 run_and_verify.py -tf -ff_depth 4 -row_n 3 -col_m 3

      - name: XY NoC 4x4
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_xy_noc
          python3 run_and_verify.py -tf -ff_depth 4 -row_n 4 -col_m 4

      - name: XY NoC 5x5
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_xy_noc
          python3 run_and_verify.py -tf -ff_depth 4 -row_n 5 -col_m 5

      - name: Upload JSONs
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: mesh_xy_noc_FF_D4
          path: sim/functional/mesh_xy_noc/*.json

  mesh_wh_xy_noc_FF_D2:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Wormhole XY NoC FF_D 2
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_wh_xy_noc
          python3 run_and_verify.py -ff_depth 2 -row_n 3 -col_m 3

      - name: Wormhole XY NoC FF_D 3
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_wh_xy_noc
          python3 run_and_verify.py -ff_depth 2 -row_n 4 -col_m 4

      - name: Wormhole XY NoC FF_D 4
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_wh_xy_noc
          python3 run_and_verify.py -ff_depth 2 -row_n 5 -col_m 5

      - name: Upload JSONs
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: mesh_wh_xy_noc_FF_D2
          path: sim/functional/mesh_wh_xy_noc/*.json

  mesh_wh_xy_noc_FF_D3:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Wormhole XY NoC 3x3
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_wh_xy_noc
          python3 run_and_verify.py -ff_depth 3 -row_n 3 -col_m 3

      - name: Wormhole XY NoC 4x4
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_wh_xy_noc
          python3 run_and_verify.py -ff_depth 3 -row_n 4 -col_m 4

      - name: Wormhole XY NoC 5x5
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_wh_xy_noc
          python3 run_and_verify.py -ff_depth 3 -row_n 5 -col_m 5

      - name: Upload JSONs
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: mesh_wh_xy_noc_FF_D3
          path: sim/functional/mesh_wh_xy_noc/*.json

  mesh_wh_xy_noc_FF_D4:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Wormhole XY NoC 3x3
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_wh_xy_noc
          python3 run_and_verify.py -ff_depth 4 -row_n 3 -col_m 3

      - name: Wormhole XY NoC 4x4
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_wh_xy_noc
          python3 run_and_verify.py -ff_depth 4 -row_n 4 -col_m 4

      - name: Wormhole XY NoC 5x5
        if: ${{ always() }}
        run: |
          export CI=0
          cd sim/functional/mesh_wh_xy_noc
          python3 run_and_verify.py -ff_depth 4 -row_n 5 -col_m 5

      - name: Upload JSONs
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: mesh_wh_xy_noc_FF_D4
          path: sim/functional/mesh_wh_xy_noc/*.json
